### ISSUE TITLE
Asynchronous Entity World Add Error with /f f

### ISSUE THREAD

**Issue by goswald** [MassiveCraft/Factions#1038]
Hello there!

I am having issues on my server with Factions, particularly when players run /f f on a faction.  When a player runs this command on his or her own faction, the faction member list information shows up fine (but the error is still displayed in console).  However, any other person outside of the faction does not get a list of members in the faction they run /f f on.  I'm not sure if this is a change to factions, or resulting from the error thrown.

If this is user error, I apologize; I have looked for information on this error and on players not seeing other faction's members.  I have not found any information regarding it, other than in another bug report from another user (which didn't have much information as to what may have caused or resolved the issue).

In any case, thank you for your time in looking at this!  If you require any additional information, please let me know.  I'm glad to provide anything that may be of use.

Error Occurs:
- When players within a faction run /f f on their own faction
- When players outside of a faction run /f f on that faction
- When server staff runs /f f on any faction
- When console runs /f f on any faction

Massive Plugins Used:
- MassiveCore v2.8.6
- MassiveLag v2.8.6 (Still learning its operation)
- MassiveBooks v2.8.6
- Factions v2.8.6

Server Jar and Version Info: [INFO] This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Error Message:
`[19:23:13] [Craft Scheduler Thread - 2/ERROR]: Could not pass event EventFactionsFactionShowAsync to Factions v2.8.6
org.bukkit.event.EventException
        at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:77) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.massivecraft.massivecore.event.EventMassiveCore.run(EventMassiveCore.java:30) [MassiveCore.jar:?]
        at com.massivecraft.factions.cmd.CmdFactionsFaction$1.run(CmdFactionsFaction.java:56) [Factions.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [?:1.7.0_07]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [?:1.7.0_07]
        at java.lang.Thread.run(Thread.java:722) [?:1.7.0_07]
Caused by: java.lang.IllegalStateException: Asynchronous entity world add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.b(World.java:2633) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:820) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:568) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.Location.getBlock(Location.java:87) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.gestern.gringotts.data.EBeanDAO.getChests(EBeanDAO.java:169) ~[?:?]
        at org.gestern.gringotts.GringottsAccount.balance(GringottsAccount.java:47) ~[?:?]
        at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:231) ~[?:?]
        at org.gestern.gringotts.api.impl.VaultConnector.getBalance(VaultConnector.java:79) ~[?:?]
        at com.massivecraft.massivecore.money.MoneyMixinVault.get(MoneyMixinVault.java:135) ~[?:?]
        at com.massivecraft.massivecore.money.Money.get(Money.java:115) ~[?:?]
        at com.massivecraft.factions.engine.EngineMain.onFactionShow(EngineMain.java:232) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_07]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_07]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_07]
        at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0_07]
        at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:60) ~[?:?]
        ... 10 more
`

**Comment by goswald** [comment]
Further inspection of the log indicates it might be something to do with Gringotts not being compiled against the most recent version of Factions.

I'm reaching out to the dev currently working on Gringotts to verify what version they compiled against.

**Comment by ulumulu1510** [comment]
Your investigation is correct.

It seems that gringots tries to access a chest in a world when our Faction Show event is run. This is very obviously an Asynchronous Event.

He can't access the bukkit API async. Thats what he has to change.
