### ISSUE TITLE
EventFactionsCreate

### ISSUE THREAD

**Issue by TheChampTF** [MassiveCraft/Factions#1045]
[17:38:16 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event EventFactionsCreate to Factions v2.8.7Beta
org.bukkit.event.EventException
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at com.massivecraft.massivecore.event.EventMassiveCore.run(EventMassiveCore.java:30) [MassiveCore.jar:?]
	at com.massivecraft.factions.cmd.CmdFactionsCreate.perform(CmdFactionsCreate.java:71) [Factions.jar:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:895) [MassiveCore.jar:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:852) [MassiveCore.jar:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:936) [MassiveCore.jar:?]
	at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) [MassiveCore.jar:?]
	at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) [PerWorldPlugins.jar:?]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1342) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1177) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-b1c1b55-dd016e7]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.hasAccount(Economy_Craftconomy3.java:254) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.ensureExists(MoneyMixinVault.java:201) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:164) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:58) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.spawn(MoneyMixinAbstract.java:83) ~[?:?]
	at com.massivecraft.massivecore.money.Money.spawn(Money.java:176) ~[?:?]
	at com.massivecraft.factions.integration.Econ.modifyMoney(Econ.java:243) ~[?:?]
	at com.massivecraft.factions.integration.Econ.payForAction(Econ.java:44) ~[?:?]
	at com.massivecraft.factions.engine.EngineEcon.payForAction(EngineEcon.java:108) ~[?:?]
	at com.massivecraft.factions.engine.EngineEcon.payForCommand(EngineEcon.java:191) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]

**Comment by MarkehMe** [comment]
This is an integration issue with Craftconomy3 / Vault. Are you using 1.9?

https://www.spigotmc.org/resources/craftconomy.2395/:
```Latest version: 3.3. Compatible with Craftbukkit 1.8```

You should try another plugin that uses Vault and see if it has a similar issue.
