### ISSUE TITLE
Factions Crashing My Server. No idea why!

### ISSUE THREAD

**Issue by Botanistt** [MassiveCraft/Factions#1051]
`[15:07:37 WARN]: [MassiveCore] Task #9 for MassiveCore v2.8.7Beta generated an exception
java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "com/massivecraft/massivecore/mixin/Mixin"
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_66-internal]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_66-internal]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_66-internal]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_66-internal]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_66-internal]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_66-internal]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_66-internal]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_66-internal]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_66-internal]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[factions.jar:git-Spigot-095e59a-2bfda1f]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[factions.jar:git-Spigot-095e59a-2bfda1f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[factions.jar:git-Spigot-095e59a-2bfda1f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[factions.jar:git-Spigot-095e59a-2bfda1f]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66-internal]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66-internal]
        at com.massivecraft.factions.entity.MPlayer.isTerritoryInfoTitles(MPlayer.java:578) ~[?:?]
        at com.massivecraft.factions.entity.MPlayer.isDefault(MPlayer.java:78) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.isDefault(Coll.java:193) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.saveToRemoteFixed(Coll.java:462) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.syncIdFixed(Coll.java:695) ~[?:?]
        at com.massivecraft.massivecore.store.CollAbstract.syncIdFixed(CollAbstract.java:236) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.syncIdentified(Coll.java:889) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.onTick(Coll.java:923) ~[?:?]
        at com.massivecraft.massivecore.store.SenderColl.onTick(SenderColl.java:38) ~[?:?]
        at com.massivecraft.factions.entity.MPlayerColl.onTick(MPlayerColl.java:34) ~[?:?]
        at com.massivecraft.massivecore.engine.EngineMassiveCoreCollTick.run(EngineMassiveCoreCollTick.java:28) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[factions.jar:git-Spigot-095e59a-2bfda1f]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [factions.jar:git-Spigot-095e59a-2bfda1f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [factions.jar:git-Spigot-095e59a-2bfda1f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [factions.jar:git-Spigot-095e59a-2bfda1f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [factions.jar:git-Spigot-095e59a-2bfda1f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [factions.jar:git-Spigot-095e59a-2bfda1f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
`

My server is constantly crashing because of factions and I have no idea why. Just got this error when typing /f f

**Comment by MarkehMe** [comment]
```attempted duplicate class definition for name: "com/massivecraft/massivecore/mixin/Mixin" at ```

This is really weird. Are you reloading? Thats a no go. Are you loading two MassiveCore plugins?

**Comment by Botanistt** [comment]
I only have 1 massivecore. I'm not reloading anything.
I'm getting constant errors and server is crashing multiple times per day.

**Comment by Botanistt** [comment]
This is my crash report http://pastebin.com/8gbwerzB
Please help me! This isn't normal!

**Comment by ulumulu1510** [comment]
@Botanistt , as far as I can tell, this crash does not origin from MassiveCore or Factions.

However the report in your first message is, but it can only happen if you have two instances of MassiveCore running. According to your crash report, everything is fine (only one MassiveCore installed). To make sure this doesn't happen again, remove all your MassivePlugins (namely CreativeGates, Factions and MassiveCore) and replace them with freshly downloaded ones.

After you have done that, make sure to restart your server. Even if you are not, take our word of advice to not reload at all! It will break our datafile storage system and will seriously screw up your data.

Another word of advice is to remove one half of the plugins (on a test server ofc.) and see when the server stops crashing. With this method, you can figure out exactly which plugin is causing it. If there is no plugin causing the issue, update your spigot (rerun buildtools) and try again. If that last step didn't help, post an error report in spigots JIRA.

Please report back whether this solution has helped you.

**Comment by Botanistt** [comment]
Thank you for your response @ulumulu1510 !
I updated spigot version and it work's flawlessly now.
I've never did /reload and also I had 1 instance of massivecore.
Thank you!
