### ISSUE TITLE
FactionTax Error

### ISSUE THREAD

**Issue by tara81** [MassiveCraft/Factions#1053]
[14:08:26] [Server thread/WARN]: [FactionsTax] Task #684860 for FactionsTax v2.8.7Beta generated an exception
java.lang.IllegalArgumentException: ArrayList is neither String nor Mson.
	at com.massivecraft.massivecore.mixin.MessageMixinDefault.messageOne(MessageMixinDefault.java:115) ~[?:?]
	at com.massivecraft.massivecore.mixin.MessageMixinDefault.messagePredicate(MessageMixinDefault.java:61) ~[?:?]
	at com.massivecraft.massivecore.mixin.MessageMixinAbstract.messagePredicate(MessageMixinAbstract.java:97) ~[?:?]
	at com.massivecraft.massivecore.mixin.Mixin.messagePredicate(Mixin.java:341) ~[?:?]
	at com.massivecraft.factions.entity.Faction.sendMessage(Faction.java:1197) ~[?:?]
	at com.massivecraft.factionstax.FactionsTax.warnDo(FactionsTax.java:197) ~[?:?]
	at com.massivecraft.factionstax.FactionsTax.warnPerhaps(FactionsTax.java:223) ~[?:?]
	at com.massivecraft.factionstax.FactionsTax.warnPerhaps(FactionsTax.java:217) ~[?:?]
	at com.massivecraft.factionstax.engine.EngineMain$3.run(EngineMain.java:190) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.jar:git-Paper-486]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.jar:git-Paper-486]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:784) [patched_1.9.jar:git-Paper-486]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-486]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-486]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-486]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by magnusulf** [comment]
Is fixed. Will be a part of next update.
