### ISSUE TITLE
Cannot pass entityExplodeEvent

### ISSUE THREAD

**Issue by robertjones6** [MassiveCraft/Factions#1055]
Hi I am getting this error on my server when i start it up

`[07:51:59] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to Factions v2.8.7Beta
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.b(EntityEnderDragon.java:433) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.n(EntityEnderDragon.java:287) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1766) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Location X should not be NaN!
	at com.massivecraft.massivecore.ps.PS.throwIfStrange(PS.java:269) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.<init>(PS.java:253) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:296) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:308) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.blockExplosion(EngineMain.java:1225) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	... 16 more
[07:51:59] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to Factions v2.8.7Beta
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.b(EntityEnderDragon.java:433) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.n(EntityEnderDragon.java:287) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1766) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Location X should not be NaN!
	at com.massivecraft.massivecore.ps.PS.throwIfStrange(PS.java:269) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.<init>(PS.java:253) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:296) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:308) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.blockExplosion(EngineMain.java:1225) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	... 16 more
[07:51:59] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to Factions v2.8.7Beta
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.b(EntityEnderDragon.java:433) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.n(EntityEnderDragon.java:287) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1766) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Location X should not be NaN!
	at com.massivecraft.massivecore.ps.PS.throwIfStrange(PS.java:269) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.<init>(PS.java:253) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:296) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:308) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.blockExplosion(EngineMain.java:1225) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	... 16 more
[07:51:59] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to Factions v2.8.7Beta
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.b(EntityEnderDragon.java:433) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.n(EntityEnderDragon.java:287) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1766) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Location X should not be NaN!
	at com.massivecraft.massivecore.ps.PS.throwIfStrange(PS.java:269) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.<init>(PS.java:253) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:296) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:308) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.blockExplosion(EngineMain.java:1225) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	... 16 more
[07:51:59] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to Factions v2.8.7Beta
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.b(EntityEnderDragon.java:433) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.n(EntityEnderDragon.java:287) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1766) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Location X should not be NaN!
	at com.massivecraft.massivecore.ps.PS.throwIfStrange(PS.java:269) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.<init>(PS.java:253) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:296) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:308) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.blockExplosion(EngineMain.java:1225) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	... 16 more
[07:51:59] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to Factions v2.8.7Beta
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.b(EntityEnderDragon.java:433) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityEnderDragon.n(EntityEnderDragon.java:287) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1766) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Location X should not be NaN!
	at com.massivecraft.massivecore.ps.PS.throwIfStrange(PS.java:269) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.<init>(PS.java:253) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:296) ~[?:?]
	at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:308) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.blockExplosion(EngineMain.java:1225) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.9_latest.jar:git-Spigot-0426685-4cd46b2]
	... 16 more`

**Comment by oloflarsson** [comment]
NaN bugs originate from the core Minecraft server itself. This is an indication of a core server fault and not a fault in Factions itself I'm afraid. If you update your server do you still get this error? They may have fixed it in Spigot itself.

**Comment by ulumulu1510** [comment]
This bug has been fixed in spigot for quite some time now, closing.
