### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by tuanjr** [MassiveCraft/Factions#1073]
```
[08:37:54] [Server thread/INFO]: BarackObama1 issued server command: /f claim circle
[08:37:55] [Server thread/INFO]: GaTrollVip11 issued server command: /tpyes
[08:37:56] [Server thread/INFO]: Ducc issued server command: /kho 1
[08:38:05] [Server thread/INFO]: BarackObama1 issued server command: /f claim square
[08:38:09] [Server thread/INFO]: guban123 issued server command: /home
[08:38:11] [Server thread/INFO]: BarackObama1 issued server command: /f claim fill
[08:38:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f claim fill' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[patched_1.9.2.jar:git-Paper-693]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1388) [patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-693]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-693]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-693]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NullPointerException: pss
	at com.massivecraft.factions.entity.MPlayer.tryClaim(MPlayer.java:847) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsSetX.perform(CmdFactionsSetX.java:53) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:890) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:847) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:847) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:931) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-693]
	... 14 more
```

**Comment by magnusulf** [comment]
Use Pastebin or a similar service for stacktraces, this is illegible.

**Comment by oloflarsson** [comment]
What version of Factions are you using? We tried patching a similar bug a couple of months ago, maybe it's fixed and you are using an old version of Factions, or we missed something and the bug is still partially there.

**Comment by tuanjr** [comment]
i'm always update latest version. When this error happen, Factions Tax Version is 2.8.10.
For now, this error wont appear any mone. But, can you fix error, player in Wilderness faction can't pvp each others?
