### ISSUE TITLE
JSON issue

### ISSUE THREAD

**Issue by Rexcantor** [MassiveCraft/Factions#1089]
I have factions 2.8.2 and I'm getting this error sometimes:

> Error: Raw data was null. Is the file completely empty?
11.05 11:21:56 [Server] INFO Collection: factions_mplayer
11.05 11:21:56 [Server] INFO Entity: e3175c4d-ad51-4da1-a4e5-2f1b6ab276fa
11.05 11:21:56 [Server] INFO Database could not load entity. You edited a file manually and made wrong JSON?

Any ideas why? It's the 3 player that the file is corrupt and it's getting annoying because the players are losing theirs facs and power!

Waiting for an answer soon,
Rexcantor64

**Comment by MarkehMe** [comment]
Is the files contents empty? check ```mstore/factions_mplayer/e3175c4d-ad51-4da1-a4e5-2f1b6ab276fa.json```

**Comment by Rexcantor** [comment]
The file is completely empty... I will check the logs to see when the message became appearing on the console. Also, is there an option to mysql storage?

**Comment by Rexcantor** [comment]
Ok... I found the error...:

> [15:46:13] [pool-6-thread-1/ERROR]: No space left on device
java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method) ~[?:1.8.0_72]
	at java.io.FileOutputStream.write(FileOutputStream.java:326) ~[?:1.8.0_72]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:1.8.0_72]
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316) ~[?:1.8.0_72]
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149) ~[?:1.8.0_72]
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233) ~[?:1.8.0_72]
	at com.earth2me.essentials.EssentialsConf$WriteRunner.run(EssentialsConf.java:426) [Essentials-2.x-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

The server ran out of space...

**Comment by MarkehMe** [comment]
No, but there is mongodb. 

Unfortunate! Happy to see you've come to a resolution though.
