### ISSUE TITLE
Factions 2.7.4 Stopped working

### ISSUE THREAD

**Issue by StarhunterUC** [MassiveCraft/Factions#1102]
```
01.06 23:30:04 [Server] INFO [Factions] Enabling Factions v2.7.4
01.06 23:30:04 [Server] INFO [Factions 2.7.4] === ENABLE START ===
01.06 23:30:04 [Server] ERROR Error occurred while enabling Factions v2.7.4 (Is it up to date?)
01.06 23:30:04 [Server] INFO java.lang.RuntimeException: Failed to invoke public com.massivecraft.factions.entity.MConf() with no args
01.06 23:30:04 [Server] INFO at com.massivecraft.massivecore.xlib.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:112) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:174) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:806) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:871) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:844) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.massivecore.store.Coll.loadFromRemote(Coll.java:626) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:859) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.massivecore.store.Coll.init(Coll.java:947) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.factions.entity.MConfColl.init(MConfColl.java:29) ~[?:?]
01.06 23:30:04 [Server] INFO at com.massivecraft.factions.Factions.onEnable(Factions.java:130) ~[?:?]
01.06 23:30:04 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-
```

**Comment by MarkehMe** [comment]
Was a word of warning, Factions v2.7.4 is outdated. But I assume you're using it for Forge purposes? 

What version of MassiveCore are you using?

http://dev.bukkit.org/bukkit-plugins/mcore/files/42-massive-core-2-7-4/

**Comment by StarhunterUC** [comment]
That would be the Version im using, and yes its for Forge purposes

**Comment by StarhunterUC** [comment]
Thing is, It dosen't Even Load up, just crashes

**Comment by ulumulu1510** [comment]
If the bug is in this specific version we can't help you. This bug has be probably been fixed for a long time. We do not offer support for outdated versions, as bugs there have already been resolved.
Please try another version that could load with forge, but other than that, you are on your own.
