### ISSUE TITLE
1.10 - See Chunks

### ISSUE THREAD

**Issue by ThePyromaniac** [MassiveCraft/Factions#1104]
When using the /f sc - /f seechunks command, in 1.10, the console is spammed repeatedly with errors. Error: 
```
[15:18:35] [Server thread/WARN]: [Factions] Task #165 for Factions v2.8.17 generated an exception
com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library
	at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1401) ~[?:?]
	at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.<init>(ParticleEffect.java:1335) ~[?:?]
	at com.massivecraft.massivecore.particleeffect.ParticleEffect.display(ParticleEffect.java:599) ~[?:?]
	at com.massivecraft.massivecore.particleeffect.ParticleEffect.display(ParticleEffect.java:618) ~[?:?]
	at com.massivecraft.massivecore.particleeffect.ParticleEffect.display(ParticleEffect.java:1609) ~[?:?]
	at com.massivecraft.factions.engine.EngineSeeChunk.run(EngineSeeChunk.java:101) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.Packet63WorldParticles
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_77]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_77]
	at com.massivecraft.massivecore.particleeffect.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:414) ~[?:?]
	at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1395) ~[?:?]
	... 12 more
```

**Comment by ThePyromaniac** [comment]
(The spoiler was a fail.)

**Comment by MarkehMe** [comment]
I fixed your indention for you.. the error says "Your current bukkit version seems to be incompatible with this library", I don't think it's ready for 1.10 yet

**Comment by oloflarsson** [comment]
This has been fixed in the latest release.
