### ISSUE TITLE
Factions dynmap will not load

### ISSUE THREAD

**Issue by pollollybearus** [MassiveCraft/Factions#1118]
I have created a completely new server only with the basic files and factions dynmap ( of course with massive core and factions jars also) and still it refuses to load, I think it may be to do with java but i have java 8 already as far as I know. Using version 1.10 of spigot

[15:29:30] [Server thread/INFO]: LiitleKoreanGirl issued server command: /pluginmanager load FactionsDynmap.jar
[15:29:30] [Server thread/WARN]: org.bukkit.plugin.UnknownDependencyException: dynmap
[15:29:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:125)
[15:29:30] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[15:29:30] [Server thread/WARN]: 	at com.jadeningle.PluginManager.Utils.Control.loadPlugin(Control.java:130)
[15:29:30] [Server thread/WARN]: 	at com.jadeningle.PluginManager.PluginManagerCommand.loadPluginCommand(PluginManagerCommand.java:161)
[15:29:30] [Server thread/WARN]: 	at com.jadeningle.PluginManager.PluginManagerCommand.onCommand(PluginManagerCommand.java:59)
[15:29:30] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:29:30] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:29:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:29:30] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:29:30] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[15:29:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
[15:29:30] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by ulumulu1510** [comment]
Do not use a plugin manager to load plugins, please always restart your server properly. Have you tried whether actually restarting does the job instead of trying to load it with another plugin?

**Comment by MarkehMe** [comment]
Also,

```[15:29:30] [Server thread/WARN]: org.bukkit.plugin.UnknownDependencyException: dynmap```

Are you sure dynmap started up?

**Comment by pollollybearus** [comment]
I'm not sure what you mean by if it's started up however when I used stop command and opened it with the start.bat (not /reload) and i got a similar error. Also it says that it is not installed when i do /f dynmap :(
[09:19:45] [Server thread/ERROR]: Could not load 'plugins\FactionsDynmap.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: dynmap
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot.jar:git-Spigot-c3e4052-1953f52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
[09:19:45] [Server thread/INFO]: Set PluginClassLoader as parallel capable

**Comment by pollollybearus** [comment]
I think I have resolved this issue, I installed just dynmap along with factions dynmap however I cant seem to get the overlay to work, any help?

**Comment by ulumulu1510** [comment]
Clearly, you will need Factions, Dynmap and Factions Dynmap installed so you have everything running.

Please specify what you mean by "overlay". The colored faction territory squares? Or something else?
In case you hadn't put all three plugins in your Plugin Folder, it is very clear to me why it didn't show any overlays, but if you did, please describe very detailed what you did, what you expected to happen and what actually happened.

**Comment by pollollybearus** [comment]
i have all three in after diving into the jar file. So atm i have Factions, Factions-Dynmap, dynmap, and MassiveCore but the map overlay which is supposed to appear in the top right of the screen is not appearing. I can't find any detailed configuration walkthrough so I don't really have any idea how to fix it, I have opened the port for dynmap and can see it online however it won't appear in game
