### ISSUE TITLE
Faction Disband Internal Error.

### ISSUE THREAD

**Issue by FrostTaco** [MassiveCraft/Factions#1130]
```
[02:06:07] [Server thread/INFO]: FrostTaco issued server command: /f disband
[02:06:07] [Server thread/ERROR]: Could not pass event EventFactionsDisband to Factions v2.8.19
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at com.massivecraft.massivecore.event.EventMassiveCore.run(EventMassiveCore.java:30) [MassiveCore.jar:?]
        at com.massivecraft.factions.cmd.CmdFactionsDisband.perform(CmdFactionsDisband.java:60) [Factions.jar:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:973) [MassiveCore.jar:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:929) [MassiveCore.jar:?]
        at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) [MassiveCore.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendFlatfile.accountExists(EconomyStorageBackendFlatfile.java:75) ~[?:?]
        at org.appledash.saneeconomy.economy.EconomyManager.accountExists(EconomyManager.java:51) ~[?:?]
        at org.appledash.saneeconomy.vault.EconomySaneEconomy.hasAccount(EconomySaneEconomy.java:54) ~[?:?]
        at com.massivecraft.massivecore.money.MoneyMixinVault.ensureExists(MoneyMixinVault.java:202) ~[?:?]
        at com.massivecraft.massivecore.money.MoneyMixinVault.get(MoneyMixinVault.java:135) ~[?:?]
        at com.massivecraft.massivecore.money.Money.get(Money.java:115) ~[?:?]
        at com.massivecraft.factions.engine.EngineEcon.takeOnDisband(EngineEcon.java:84) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        ... 23 more
[02:06:07] [Server thread/INFO]: [Factions 2.8.19] The faction test (fc7e8d27-e1f3-4d8c-83fd-71148bad8
ad4) was disbanded by FrostTaco.
[02:06:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f disband' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendFlatfile.accountExists(EconomyStorageBackendFlatfile.java:75) ~[?:?]
        at org.appledash.saneeconomy.economy.EconomyManager.accountExists(EconomyManager.java:51) ~[?:?]
        at org.appledash.saneeconomy.vault.EconomySaneEconomy.hasAccount(EconomySaneEconomy.java:54) ~[?:?]
        at com.massivecraft.massivecore.money.MoneyMixinVault.exists(MoneyMixinVault.java:119) ~[?:?]
        at com.massivecraft.massivecore.money.Money.exists(Money.java:99) ~[?:?]
        at com.massivecraft.factions.entity.Faction.preDetach(Faction.java:85) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.preDetach(Coll.java:357) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.detachFixed(Coll.java:330) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.detachEntity(Coll.java:308) ~[?:?]
        at com.massivecraft.massivecore.store.Entity.detach(Entity.java:76) ~[?:?]
        at com.massivecraft.factions.cmd.CmdFactionsDisband.perform(CmdFactionsDisband.java:90) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:973) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:929) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-cf6dea3-ca1bb1c]
        ... 14 more


```

**Comment by MarkehMe** [comment]
I've had to modify your ticket to make it easier to read in the future please wrap your log blocks with back quotes (```)  like so:

```
Like this : ``` your log here ```
```

---

This appears to be an error with your economy plugin or Vault, please open a ticket with SaneEconomy
