### ISSUE TITLE
crazy-enchantments Compatibility error

### ISSUE THREAD

**Issue by zsgaming** [MassiveCraft/Factions#1131]
```
[23:34:02] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CrazyEnchantments v1.6.4.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at me.BadBones69.CrazyEnchantments.MultiSupport.FactionsSupport.isFriendly(FactionsSupport.java:17) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Api.isFriendly(Api.java:228) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Enchantments.Armor.onMovment(Armor.java:421) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	... 15 more
```

**Comment by MarkehMe** [comment]
This is not an issue with Factions but an issue with CrazyEnchantments, so unfortunately we can't be of much help. 😞 

I see you have opened up an issue ticket @ https://github.com/kicjow/Crazy-Enchantments/issues/61 so I will close this.

**Comment by zsgaming** [comment]
Okay thanks for the reply i just figured it wasn't yours. its a Enhancement called Angel.

**Comment by MarkehMe** [comment]
Hope it gets fixed up quickly, be sure to supply as much information as possible to the other developer about your server (plugins and their versions, etc)
