### ISSUE TITLE
Factions doesnt load

### ISSUE THREAD

**Issue by VictrixNetwork** [MassiveCraft/Factions#1144]
Hey i have been working on a factions server for a while and now im not sure what has happened.
That is a paste of a section from the console. 
```
>pl
[23:51:17 INFO]: Plugins (60): Beast-XpWithDraw, SimpleBroadcast, ItemToCommand, PlugMan, FancyPortals, CloudTrade, aAntiSpam, AntiCriticalCheat, ViaVersion, Tablist, ParticleText, CoreProtect, WorldEdit, CrazyEnchantments, NoSwear, BukkitCompat, Votifier, Multiverse-Core, AutoSaveWorld, NightVision, NoHopper, ObsidianBreaker, JoinFullServer, ItemCases, iConomy, PermissionsEx, Lottery, AnvilColors, BetterSpawnEggs, Multiverse-Portals, GAListener, Vault, PotionShop, MassiveCore, EnderPearlCoolDown, MoneyPouch, WorldGuard, MobStacker, ChestCommands, PlayerVaults, GuiShop, Essentials, NoItem, SpigotLib, Banknotes, ProtocolLib, NoCheatPlus, Citizens, EssentialsChat, EnjinMinecraftPlugin, ChestShop, HolographicDisplays, Factions, SupplyCrates, CommandNPC, StaffPlus, EssentialsSpawn, ItemHover, CombatLog, SilkSpawners
>/? factions
[23:51:30 INFO]: < [Victrix Factions] Unknown command please try '/Help' >
>? factions
[23:51:36 INFO]: No help for factions
>plugman reload factions
[23:51:49 INFO]: [Factions] Disabling Factions v2.8.20
[23:51:49 INFO]: [Factions 2.8.20] Disabled
[23:51:49 INFO]: [Factions] Enabling Factions v2.8.20
[23:51:49 INFO]: [Factions 2.8.20] === ENABLE START ===
[23:51:49 ERROR]: Error occurred while enabling Factions v2.8.20 (Is it up to date?)
com.massivecraft.massivecore.xlib.gson.JsonSyntaxException: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated object at line 269 column 4 path $.econEnabled
        at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:57) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJson(DriverFlatfile.java:167) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFile(DriverFlatfile.java:154) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadAll(DriverFlatfile.java:193) ~[?:?]
        at com.massivecraft.massivecore.store.DbAbstract.loadAll(DbAbstract.java:68) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:924) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:1072) ~[?:?]
        at com.massivecraft.factions.entity.MConfColl.setActive(MConfColl.java:32) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:132) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:316) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:377) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated object at line 269 column 4 path $.econEnabled
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.syntaxError(JsonReader.java:1574) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.doPeek(JsonReader.java:496) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.hasNext(JsonReader.java:419) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:1) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:45) ~[?:?]
        ... 29 more
[23:51:49 INFO]: [PlugMan] Factions has been reloaded.
>f
[23:52:04 INFO]: < [Victrix Factions] Unknown command please try '/Help' >
>
```

**Comment by MarkehMe** [comment]
Do not use **PlugMan**, restart your server.

**Comment by VictrixNetwork** [comment]
Hey still doesnt work. 

[12:15:28 INFO]: [Factions 2.8.20] === ENABLE START ===
[12:15:28 ERROR]: Error occurred while enabling Factions v2.8.20 (Is it up to date?)
com.massivecraft.massivecore.xlib.gson.JsonSyntaxException: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated object at line 269 column 4 path $.econEnabled
        at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:57) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJson(DriverFlatfile.java:167) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFile(DriverFlatfile.java:154) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadAll(DriverFlatfile.java:193) ~[?:?]
        at com.massivecraft.massivecore.store.DbAbstract.loadAll(DbAbstract.java:68) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:924) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:1072) ~[?:?]
        at com.massivecraft.factions.entity.MConfColl.setActive(MConfColl.java:32) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:132) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated object at line 269 column 4 path $.econEnabled
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.syntaxError(JsonReader.java:1574) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.doPeek(JsonReader.java:496) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.hasNext(JsonReader.java:419) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:1) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:45) ~[?:?]
        ... 23 more

**Comment by MarkehMe** [comment]
**Unterminated object at line 269 column 4 path $.econEnabled**

Please run your .json file through http://jsonlint.com/ as there is an issue near ```econEnabled```. You probably forgot a comma, or something.

**Comment by VictrixNetwork** [comment]
hey I havnt changed any of the configs and im not sure which .json you mean

**Comment by UnoGib** [comment]
@MarkehMe I use http://www.aternos.org/ and it used to run factions 1.8, now it doesn't. I have mcore and factions installed. Any other plugins? When I do /help Factions it comes up with no commands. You can come on the server and I can give you access to config aswell.

**Comment by ulumulu1510** [comment]
Reloading our plugins breaks the json-serialization/deserialisation and can possibly corrupt your file. 

Never reload factions, it isn't necessary at all since all changes in the configuration files are reflected life within seconds.

If you haven't changed much in the configuration,  delete it and let factions regenerate this file for you. And from now on, never reload it again.
