### ISSUE TITLE
Factions doesnt load

### ISSUE THREAD

**Issue by VictrixNetwork** [MassiveCraft/Factions#1147]
Help!! please

[17:13:59 INFO]: [Factions 2.8.11] === ENABLE START ===
[17:13:59 ERROR]: Error occurred while enabling Factions v2.8.11 (Is it up to date?)
com.massivecraft.massivecore.xlib.gson.JsonSyntaxException: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated object at line 269 column 4 path $.econEnabled
        at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:57) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJson(DriverFlatfile.java:167) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFile(DriverFlatfile.java:154) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadAll(DriverFlatfile.java:193) ~[?:?]
        at com.massivecraft.massivecore.store.DbAbstract.loadAll(DbAbstract.java:68) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:918) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:1012) ~[?:?]
        at com.massivecraft.factions.entity.MConfColl.setActive(MConfColl.java:39) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:131) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:125) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated object at line 269 column 4 path $.econEnabled
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.syntaxError(JsonReader.java:1574) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.doPeek(JsonReader.java:496) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.hasNext(JsonReader.java:419) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:1) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:45) ~[?:?]
        ... 23 more

**Comment by MarkehMe** [comment]
Do not open additional issue tickets, stick to your one ticket.
