### ISSUE TITLE
Skript and Faction are incompatible

### ISSUE THREAD

**Issue by DianoxDragon** [MassiveCraft/Factions#1159]
`[16:02:16] [Server thread/INFO]: Dianox issued server command: /skript reload stats
[16:02:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'skript' in plugin Skript v2.2-SNAPSHOT
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

> **Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.Rel.parse(Ljava/lang/String;)Lcom/massivecraft/factions/Rel;**

at uk.co.umbaska.Managers.Enums$6.parse(Enums.java:299) ~[?:?]
at uk.co.umbaska.Managers.Enums$6.parse(Enums.java:295) ~[?:?]
at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:400) ~[?:?]
at ch.njol.skript.registrations.Classes.parse(Classes.java:429) ~[?:?]
at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97) ~[?:?]
at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86) ~[?:?]
at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:174) ~[?:?]
at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:126) ~[?:?]
at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:244) ~[?:?]
at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:171) ~[?:?]
at ch.njol.skript.lang.Condition.parse(Condition.java:83) ~[?:?]
at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:729) ~[?:?]
at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:510) ~[?:?]
at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:268) ~[?:?]
at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:155) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
... 15 more`

I can't make my skript...

**Comment by ulumulu1510** [comment]
Your Skript plugin references old API methods of ours and is thus incompatible. Please referente this issue and my answer on a ticket to the Skript plugin.
