### ISSUE TITLE
Error loading Factions/MassiveCore in craftbukkit

### ISSUE THREAD

**Issue by kekusmaximus** [MassiveCraft/Factions#1169]
Today I tried to install these plugins and gave me this error

[13:52:58] [Server thread/INFO]: Starting minecraft server version 1.11
[13:52:58] [Server thread/INFO]: Loading properties
[13:52:58] [Server thread/INFO]: Default game type: SURVIVAL
[13:52:58] [Server thread/INFO]: Generating keypair
[13:52:59] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:52:59] [Server thread/INFO]: Using default channel type
[13:52:59] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-b64d852 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
[13:52:59] [Server thread/ERROR]: Could not load 'plugins\MassiveCore.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/massivecraft/massivecore/MassiveCore : Unsupported major.minor version 51.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:297) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.<init>(CraftServer.java:259) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at net.minecraft.server.v1_11_R1.PlayerList.<init>(PlayerList.java:73) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:185) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at java.lang.Thread.run(Unknown Source) [?:1.6.0_37]
Caused by: java.lang.UnsupportedClassVersionError: com/massivecraft/massivecore/MassiveCore : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_37]
	at java.lang.ClassLoader.defineClassCond(Unknown Source) ~[?:1.6.0_37]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.6.0_37]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.6.0_37]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.6.0_37]
	at java.net.URLClassLoader.access$000(Unknown Source) ~[?:1.6.0_37]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.6.0_37]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_37]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.6.0_37]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.6.0_37]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.6.0_37]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_37]
	at java.lang.Class.forName(Unknown Source) ~[?:1.6.0_37]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[craftbukkit-1.11.jar:git-Bukkit-b64d852]
	... 9 more
[13:52:59] [Server thread/ERROR]: Could not load 'plugins\Factions.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MassiveCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:297) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.<init>(CraftServer.java:259) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at net.minecraft.server.v1_11_R1.PlayerList.<init>(PlayerList.java:73) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:185) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-1.11.jar:git-Bukkit-b64d852]
	at java.lang.Thread.run(Unknown Source) [?:1.6.0_37]

I installed Essentials as well and it works and I don't know what else to do because there's not much info about this.

**Comment by kekusmaximus** [comment]
Sorry I think I've figured it out :D
