### ISSUE TITLE
Could not load 'plugins\FactionsDynmap.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by TomPiXX** [MassiveCraft/Factions#1185]
We're running a Thermos 1.7.10 (Cauldron fork) server and have to use DynmapForge (https://minecraft.curseforge.com/projects/dynmapforge/files/2307078).

We're getting the following error:

`[08:12:05] [Server thread/ERROR]: Could not load 'plugins\FactionsDynmap-2.10.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: dynmap
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:223) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
`

**Comment by TomPiXX** [comment]
Nevermind: We had to add DynmapCBBridge. Sorry for the false report.
