### ISSUE TITLE
MalformedJson?

### ISSUE THREAD

**Issue by Spazzinq** [MassiveCraft/Factions#1198]
Error occurred while enabling Factions v2.10.0 (Is it up to date?)
com.massivecraft.massivecore.xlib.gson.JsonSyntaxException: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Expected name at line 2 column 1 path $.
        at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:57) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJson(DriverFlatfile.java:167) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFile(DriverFlatfile.java:154) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadAll(DriverFlatfile.java:193) ~[?:?]
        at com.massivecraft.massivecore.store.DbAbstract.loadAll(DbAbstract.java:68) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:924) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:1072) ~[?:?]
        at com.massivecraft.factions.entity.MConfColl.setActive(MConfColl.java:32) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:133) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Expected name at line 2 column 1 path $.
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.syntaxError(JsonReader.java:1575) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.doPeek(JsonReader.java:518) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.hasNext(JsonReader.java:419) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:45) ~[?:?]
        ... 23 more

**Comment by MarkehMe** [comment]
The formatting in your Factions MConf is incorrect around lines 1 - 3, it has to be in valid JSON format.

If you can't see the issues with the JSON you can [paste it into this online tool](http://jsonlint.com/) and it will point out the error for you :)

**Comment by Spazzinq** [comment]
Found it I had an extra line ;)

**Comment by MarkehMe** [comment]
Great to hear :)
