### ISSUE TITLE
Unhandled exception executing 'f money

### ISSUE THREAD

**Issue by TomberWolf** [MassiveCraft/Factions#1199]
We're on Thermos 1.7.10. Everything works fine with some exceptions.

`[12:21:08] [Server thread/INFO]: Foggar issued server command: /f money pf 63 Foggar NORDICSCOUNDRELS
[12:21:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f money pf 63 Foggar NORDICSCOUNDRELS' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.utils.MISCUtils.getItemCount(MISCUtils.java:142) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getBalance(AccountUtils.java:105) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:171) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.work(Transaction.java:240) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.perform(Transaction.java:53) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:159) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:153) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsAdd(TNEAPI.java:90) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsAdd(TNEAPI.java:80) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.depositPlayer(TNEVaultEconomy.java:338) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:180) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:64) ~[?:?]
	at com.massivecraft.massivecore.money.Money.move(Money.java:146) ~[?:?]
	at com.massivecraft.factions.integration.Econ.transferMoney(Econ.java:142) ~[?:?]
	at com.massivecraft.factions.integration.Econ.transferMoney(Econ.java:101) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsMoneyTransferPf.perform(CmdFactionsMoneyTransferPf.java:53) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:973) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:929) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:929) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	... 12 more`

**Comment by MarkehMe** [comment]
Duplicate. See #1199
