### ISSUE TITLE
Unhandled exception executing 'f money b'

### ISSUE THREAD

**Issue by TomberWolf** [MassiveCraft/Factions#1200]
On Thermos 1.7.10:

```[12:22:30] [Server thread/INFO]: Foggar issued server command: /f money b
[12:22:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f money b' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.utils.MISCUtils.getItemCount(MISCUtils.java:142) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getBalance(AccountUtils.java:105) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:171) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:167) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:163) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.getBalance(TNEAPI.java:175) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.getBalance(TNEVaultEconomy.java:359) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.get(MoneyMixinVault.java:136) ~[?:?]
	at com.massivecraft.massivecore.money.Money.get(Money.java:115) ~[?:?]
	at com.massivecraft.factions.integration.Econ.sendBalanceInfo(Econ.java:66) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsMoneyBalance.perform(CmdFactionsMoneyBalance.java:41) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:973) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:929) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:929) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	... 12 more
```

**Comment by MarkehMe** [comment]
Your issue seems to be related to [TNE-Bukkit](https://github.com/TheNewEconomy/TNE-Bukkit)

**Comment by MarkehMe** [comment]
You may want to direct those developers here for some more information:

The Vault call for this is `Economy#getBalance(String string)`

https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/money/MoneyMixinVault.java#L136

It appears the error comes from their end at `MISCUtils#getItemCount`

**Comment by TomberWolf** [comment]
Thanks for the hint!

**Comment by MarkehMe** [comment]
Good luck! :)
