### ISSUE TITLE
Error occurred while enabling MassiveCore v2.11.0 (Is it up to date?)

### ISSUE THREAD

**Issue by L4BORG** [MassiveCraft/Factions#1220]
```[17:42:11] [Server thread/ERROR]: Error occurred while enabling MassiveCore v2.11.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/scoreboard/Team$Option
    at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_121]
    at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_121]
    at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_121]
    at com.massivecraft.massivecore.util.ReflectionUtil.getField(ReflectionUtil.java:296) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin$1.apply(MassivePlugin.java:357) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin$1.apply(MassivePlugin.java:351) ~[?:?]
    at com.massivecraft.massivecore.predicate.PredicateAnd.apply(PredicateAnd.java:49) ~[?:?]
    at com.massivecraft.massivecore.predicate.PredicateAnd.apply(PredicateAnd.java:49) ~[?:?]
    at com.massivecraft.massivecore.util.ReflectionUtil.getPackageClasses(ReflectionUtil.java:487) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:436) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.getClassesActiveNms(MassivePlugin.java:350) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:332) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:322) ~[?:?]
    at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:234) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.bukkit.scoreboard.Team$Option
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
    ... 23 more
```

**Comment by L4BORG** [comment]
```[17:46:54 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
```
