### ISSUE TITLE
Error on Spigot 1.12

### ISSUE THREAD

**Issue by TheIntelloBox** [MassiveCraft/Factions#1227]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.12.0
- **MassiveCore Version:** 2.12.0

## Describe your environment

- **Spigot version:** git-Spigot-d5dfb24-ed8c725 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

Error : https://hastebin.com/osicunizej.sql

**Comment by MarkehMe** [comment]
`java.lang.NoClassDefFoundError: com/massivecraft/massivecore/store/EntityInternal`

Are you sure you have MassiveCore, and the correct version? Please confirm.

**Comment by Dannymc997** [comment]
its not working for me either 

[Factions 2.12.0] === ENABLE START ===
[12:14:15 ERROR]: Error occurred while enabling Factions v2.12.0 (Is it up to date?)
java.lang.NullPointerException: null
        at com.massivecraft.massivecore.MassivePlugin.checkVersionSynchronization(MassivePlugin.java:117) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnablePre(MassivePlugin.java:96) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-87496df-ed8c725]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-87496df-ed8c725]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-87496df-ed8c725]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-87496df-ed8c725]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-87496df-ed8c725]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]       
i'm running spigot 1.12

**Comment by TheIntelloBox** [comment]
Markehme, in the latest .zip the massive core version is 2,10.0 in-game.

**Comment by NerdyPacman** [comment]
How do you see the massive core version in game?

**Comment by TheIntelloBox** [comment]
./ver MassiveCore

**Comment by ulumulu1510** [comment]
Always run the same version of MassiveCore and other Massiveplugins (including Factions). Your console will have warned you about this and indeed, the EntityInternal class has not been added yet to the 2.10 version. 

Please update to 2.13 and use this version for all of your MassivePlugins (including Factions), otherwise there is no guarantee that it will work.
