### ISSUE TITLE
Factions/massivecore 2.12.0 not working on spigot 1.12

### ISSUE THREAD

**Issue by Dannymc997** [MassiveCraft/Factions#1228]
## Affected Plugin

Factions 2.12.0 MassiveCore 2.12.0

## Describe your environment
the plugins are not working
## Steps to reproduce this bug

  1. installed factions and massive core into my server
  2. started my server
  3. Error with both plugins

**Observed results**
plugins not able to start

**Expected results**
The plugins should start and run properly

**Comment by Dannymc997** [comment]
[Factions 2.12.0] === ENABLE START ===
[12:14:15 ERROR]: Error occurred while enabling Factions v2.12.0 (Is it up to date?)
java.lang.NullPointerException: null
        at com.massivecraft.massivecore.MassivePlugin.checkVersionSynchronization(MassivePlugin.java:117) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnablePre(MassivePlugin.java:96) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-87496df-ed8c725]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-87496df-ed8c725]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-87496df-ed8c725]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-87496df-ed8c725]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-87496df-ed8c725]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-87496df-ed8c725]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by NerdyPacman** [comment]
I have the same problem.

**Comment by SnakeDaoust1232** [comment]
Not working on 1.8 either. lol my entire server got griefed.

**Comment by NerdyPacman** [comment]
Do you have MassiveCore? Also, I use WorldGuard to protect spawn and shop and PvP arena. I find it better suited than Factions for admin use. Factions should be for the players not the admins to use. Try getting worldguard.

**Comment by Goldapfel** [comment]
I have the same problem too..

**Comment by ulumulu1510** [comment]
This problem seems to be originating from MassiveCore and not Factions. Anyhow, update to MassiveCore&Factions 2.13 and make an Issue report on the MassiveCore repository to report the bug. Also include the full log of your server (upload it to pastebin), otherwise we can't figure out the core of the issue.
