### ISSUE TITLE
ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer cannot be cast to com.massivecraft.factions.entity.Faction

### ISSUE THREAD

**Issue by GAME4PLAY** [MassiveCraft/Factions#1306]
[20:17:24 WARN]:        at com.ngxdev.faction.scoreboard.adapters.FactionsV2.getRelation(FactionsV2.java:20)
[20:17:24 WARN]:        at com.ngxdev.faction.nametags.FactionNameManager.run(FactionNameManager.java:28)
[20:17:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[20:17:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:17:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[20:17:24 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:17:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[20:17:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[20:17:24 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by GAME4PLAY** [comment]
Guys im using the same fac and massivecore version btw
How can i fix it plz :=)
and tnx

**Comment by TheComputerGeek2** [comment]
@GAME4PLAY it appears you not using Massive's faction plugin at all, either that or the provided stacktrace is incomplete such that key information is being left out.

**Comment by GAME4PLAY** [comment]
@TheComputerGeek2 Tnx boi im gonna try it 
<3
