### ISSUE TITLE
Faction Missing Folder

### ISSUE THREAD

**Issue by UViolets** [MassiveCraft/Factions#1308]
log:

[08:06:42] [Server thread/ERROR]: Error occurred while enabling Factions v2.13.7 (Is it up to date?)
java.lang.NoSuchMethodError: com.massivecraft.massivecore.store.migrator.MigratorUtil.addJsonRepresentation(Ljava/lang/Class;Ljava/lang/reflect/Type;)V
at com.massivecraft.factions.Factions.onEnableInner(Factions.java:77) ~[?:?]
at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft_server.jar:git-Bukkit-d0a3620]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [minecraft_server.jar:git-Bukkit-d0a3620]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [minecraft_server.jar:git-Bukkit-d0a3620]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [minecraft_server.jar:git-Bukkit-d0a3620]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [minecraft_server.jar:git-Bukkit-d0a3620]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

i recently installed Factions and MassiveCore, then i do /plugman load Factions and /plugman load MassiveCore, it's showing in /pl but the Factions plugin file is not showing in my plugins file. first, /f is works but my prefix is changed like this : <Dreafture>. then i'm restaring the server, and when i type /f help or any, its not working, it said "Unknown command. type "/help" for help."

My server is using 1.12.2,
Factions 2.13.6 and MassiveCore 2.13.6
Help me Pleaseu :(

**Comment by CS-Birb** [comment]
Hi,

Can you verify that your plugin versions are up to date?

You've stated that you're using 2.13.6, but the logs indicate that the versions of Factions you are trying to load is 2.13.7

This error suggests that your MassiveCore version needs to be updated.

Let us know if this helps.

~ 🐦

**Comment by UViolets** [comment]
it is the latest version @CS-Birb

**Comment by markhughes** [comment]
@UViolets updated MassiveCore :)
