### ISSUE TITLE
Error MassiveCore and Faction

### ISSUE THREAD

**Issue by Xeerac** [MassiveCraft/Factions#1342]
Error MassiveCore latest version install > https://dev.bukkit.org/projects/mcore/files

[20:59:56] [Server thread/ERROR]: Error occurred while enabling MassiveCore v2.14.0 (Is it up to date?)
java.lang.RuntimeException: Failed to create a flatfile system pusher.
	at com.massivecraft.massivecore.store.DriverFlatfile.getPusher(DriverFlatfile.java:270) ~[?:?]
	at com.massivecraft.massivecore.store.DbAbstract.getPusher(DbAbstract.java:87) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.getPusher(Coll.java:110) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:947) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:989) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:247) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:235) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:211) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
	at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:241) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[faction.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [faction.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [faction.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [faction.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [faction.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.io.IOException: User limit of inotify watches reached
	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264) ~[?:1.8.0_181]
	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260) ~[?:1.8.0_181]
	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364) ~[?:1.8.0_181]
	... 1 more

Error Faction, latest version install > https://dev.bukkit.org/projects/factions/files

[21:00:13] [Server thread/ERROR]: Error occurred while enabling Factions v2.14.0 (Is it up to date?)
java.lang.NullPointerException
	at com.massivecraft.massivecore.MassivePlugin.checkVersionSynchronization(MassivePlugin.java:117) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnablePre(MassivePlugin.java:96) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[faction.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [faction.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [faction.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [faction.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [faction.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by crazybytes** [comment]
Same here...
Compiled from scratch, overcome many obstacles. Succes .jar files, put in bukkit mod dir, same failures....
