### ISSUE TITLE
Tablecloth-1.12.2 and CatServer.

### ISSUE THREAD

**Issue by naemniks1996** [MassiveCraft/Factions#1355]
Hello. I tried to run on the kernels that helped interact with mods and plugins.
tablecloth-1.12.2 and CatServer.

Help me please. Thank.

[02:23:58] [Server thread/INFO] []: [Factions 2.14.0] === ENABLE START ===
[02:24:00] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Factions v2.14.0 (Is it up to date?)
java.lang.IllegalStateException: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAllies
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:331) ~[?:?]
	at com.massivecraft.massivecore.util.ReflectionUtil.getPackageClasses(ReflectionUtil.java:481) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:446) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:416) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.getClassesActiveIntegrations(MassivePlugin.java:391) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:337) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
	at com.massivecraft.factions.Factions.onEnableInner(Factions.java:80) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:433) [CraftServer.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:382) [CraftServer.class:git-CatServer-1.12.2-78df914]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAllies
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:195) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:98) ~[ReflectionMethods.class:git-CatServer-1.12.2-78df914]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 17 more
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/integration/herochat/ChannelFactionsAbstract
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:98) ~[ReflectionMethods.class:git-CatServer-1.12.2-78df914]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAbstract
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:195) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:98) ~[ReflectionMethods.class:git-CatServer-1.12.2-78df914]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 17 more
Caused by: java.lang.NoClassDefFoundError: com/dthielke/herochat/Channel
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:98) ~[ReflectionMethods.class:git-CatServer-1.12.2-78df914]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: com.dthielke.herochat.Channel
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:127) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-CatServer-1.12.2-78df914]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at catserver.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:98) ~[ReflectionMethods.class:git-CatServer-1.12.2-78df914]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 17 more

**Comment by naemniks1996** [comment]
**tablecloth-1.12.2:**
(02:19:14|INFO|): [Factions 2.14.0] === ENABLE START ===
(02:19:17|ERROR|Minecraft): Error occurred while enabling Factions v2.14.0 (Is it up to date?)
java.lang.IllegalStateException: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAllies
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:331) ~[?:?]
	at com.massivecraft.massivecore.util.ReflectionUtil.getPackageClasses(ReflectionUtil.java:481) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:446) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:416) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.getClassesActiveIntegrations(MassivePlugin.java:391) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.getClassesActive(MassivePlugin.java:337) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
	at com.massivecraft.factions.Factions.onEnableInner(Factions.java:80) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:1.12.2-2836]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [JavaPluginLoader.class:1.12.2-2836]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [SimplePluginManager.class:1.12.2-2836]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:419) [CraftServer.class:1.12.2-2836]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:368) [CraftServer.class:1.12.2-2836]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:497) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:411) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAllies
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:195) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at tablecloth.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:106) ~[ReflectionMethods.class:1.12.2-2836]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/integration/herochat/ChannelFactionsAbstract
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at tablecloth.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:106) ~[ReflectionMethods.class:1.12.2-2836]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 19 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.massivecraft.factions.integration.herochat.ChannelFactionsAbstract
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:195) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at tablecloth.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:106) ~[ReflectionMethods.class:1.12.2-2836]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/dthielke/herochat/Channel
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at tablecloth.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:106) ~[ReflectionMethods.class:1.12.2-2836]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 19 more
Caused by: java.lang.ClassNotFoundException: com.dthielke.herochat.Channel
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:127) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:187) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:119) ~[PluginClassLoader.class:1.12.2-2836]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:1.12.2-2836]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at tablecloth.server.remapper.ReflectionMethods.loadClass(ReflectionMethods.java:106) ~[ReflectionMethods.class:1.12.2-2836]
	at com.massivecraft.massivecore.xlib.guava.reflect.ClassPath$ClassInfo.load(ClassPath.java:328) ~[?:?]
	... 19 more
