### ISSUE TITLE
/f map glitches very often

### ISSUE THREAD

**Issue by ItsHarry** [MassiveCraft/Factions#218]
18:53:37 [INFO] ItsHarry issued server command: /f map
18:53:37 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
        at org.bukkit.craftbukkit.v1_4_6.CraftServer.dispatchCommand(CraftServer.java:554)
        at net.minecraft.server.v1_4_6.PlayerConnection.handleCommand(PlayerConnection.java:990)
        at net.minecraft.server.v1_4_6.PlayerConnection.chat(PlayerConnection.java:908)
        at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:852)
        at net.minecraft.server.v1_4_6.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
        at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
        at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:585)
        at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
        at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:481)
        at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:416)
        at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 65
        at com.massivecraft.factions.Board.getMap(Board.java:251)
        at com.massivecraft.factions.cmd.CmdMap.showMap(CmdMap.java:64)
        at com.massivecraft.factions.cmd.CmdMap.perform(CmdMap.java:58)
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:126)
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:59)
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116)
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:59)
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:131)
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:229)
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:189)
        at com.massivecraft.factions.P.handleCommand(P.java:189)
        at com.massivecraft.factions.P.onCommand(P.java:199)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 15 more

**Comment by MarkehMe** [comment]
Using an actual map would be cool. @oloflarsson would this be something safe to implement?

**Comment by ulumulu1510** [comment]
How would you go about adding an actual map (do you mean the minecraft ones?) of the command? It sounds interresting and it would surely get rid of the charakter limit  (colors have lots of values ^^). Do you mind ellaborating what you ment @MarkehMe ?

**Comment by FayneAldan** [comment]
Yeah, I meant a Minecraft map. But as I said, it would only show territory on the map, and not actual terrain, so that it's not just a free map command. You can probably do it by spawning a map with a special name (i.e. "Faction Map"), and modify what's shown on the map when it has that name, and delete the item if the player drops it, renames it (in an anvil), right clicks with it, etc.
In addition, you could probably also show players on the map only if they're in your own faction (same as how regular maps show other players).

**Comment by ulumulu1510** [comment]
There are all the ones I can offer to you: 85 characters, nearly 20 more than before.
/#ç*+~!|()[]{}=£¬<>@?$%=&^ABCDEFGHJKLMNOPQRSTUVWXYZ1234567890abcdeghjmnopqrsuvwxyzäöü

You can see them well on the screen and I hope this cures some of the problems. I know that It will not solve the issue if you have a different faction for every chunk on a map, but there are no 384 characters which are well readable on screen. If this pops up in the future again, we might need to consider searching for more readable/distinguishable characters, maybe from another alphabet.

https://github.com/ulumulu1510/Factions/commit/b34d92498ed28d1261713aa1fefc3f34f95f756c

**Comment by ulumulu1510** [comment]
This change, with some additional obfuscation if there still are too many factions on the map, we have pulled the change in the master branch.
