### ISSUE TITLE
Eu encontrei erros ou falhado

### ISSUE THREAD

**Issue by blur92** [MassiveCraft/Factions#417]
Hello, Factions!
I am portuguese

Não sei o que é erros.
Eu gostaria de saber.

>19:50:31 [INFO] [0;36;22m[[0;36;1mFactions 2.1.0[0;36;22m] [0;33;1m[0;31;1mNon existing factionId [0;35;1m828 [0;31;1mrequested. [0;33;1mCleaning all boards and uplayers.[m
>19:50:31 [INFO] [0;36;22m[[0;36;1mFactions 2.1.0[0;36;22m] [0;33;1mBoard cleaner removed 828 from PS{cx: -76, cz: 3}[m
>19:50:31 [SEVERE] Could not pass event PlayerMoveEvent to Factions v2.1.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:227)
at net.minecraft.server.v1_6_R2.Packet10Flying.handle(SourceFile:136)
at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:230)
at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:132)
at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:592)
at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:239)
at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:481)
at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:413)
at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NullPointerException
at com.massivecraft.factions.listeners.FactionsListenerMain.chunkChangeTerritoryInfo(FactionsListenerMain.java:134)
at com.massivecraft.factions.listeners.FactionsListenerMain.chunkChangeDetect(FactionsListenerMain.java:117)
at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
... 15 more

**Comment by oloflarsson** [comment]
You seem to be using an old version of Factions. Update to the latest version and try again please.
