### ISSUE TITLE
Factions 2.7.5 (Plugin Factions v2.7.5 generated an exception while executing task 997, 2008, 3766, 6077, 8362, 10611, 12800, 15135, 17415, 19626, 21787, 23933)

### ISSUE THREAD

**Issue by xtomyserrax** [MassiveCraft/Factions#745]
Hey i found this on the console log when i open the server:

[22:25:00] [pool-3-thread-13/WARN]: Exception in thread "pool-3-thread-13" 
[22:25:00] [pool-3-thread-13/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 997
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[22:30:00] [pool-3-thread-14/WARN]: Exception in thread "pool-3-thread-14" 
[22:30:00] [pool-3-thread-14/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 2008
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[22:35:00] [pool-3-thread-16/WARN]: Exception in thread "pool-3-thread-16" 
[22:35:00] [pool-3-thread-16/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 3766
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[22:40:00] [pool-3-thread-21/WARN]: Exception in thread "pool-3-thread-21" 
[22:40:00] [pool-3-thread-21/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 6077
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[22:45:00] [pool-3-thread-29/WARN]: Exception in thread "pool-3-thread-29" 
[22:45:00] [pool-3-thread-29/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 8362
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

--- And separated i found this too: ---

[22:50:00] [pool-3-thread-30/WARN]: Exception in thread "pool-3-thread-30" 
[22:50:00] [pool-3-thread-30/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 10611
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[22:55:00] [pool-3-thread-33/WARN]: Exception in thread "pool-3-thread-33" 
[22:55:00] [pool-3-thread-33/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 12800
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[23:00:00] [pool-3-thread-43/WARN]: Exception in thread "pool-3-thread-43" 
[23:00:00] [pool-3-thread-43/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 15135
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[23:05:00] [pool-3-thread-46/WARN]: Exception in thread "pool-3-thread-46" 
[23:05:00] [pool-3-thread-46/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 17415
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[23:10:00] [pool-3-thread-54/WARN]: Exception in thread "pool-3-thread-54" 
[23:10:00] [pool-3-thread-54/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 19626
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[23:15:00] [pool-3-thread-58/WARN]: Exception in thread "pool-3-thread-58" 
[23:15:00] [pool-3-thread-58/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 21787
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

--- And separated i found this too: ---

[23:20:00] [pool-3-thread-59/WARN]: Exception in thread "pool-3-thread-59" 
[23:20:00] [pool-3-thread-59/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 23933
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
    at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
    at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
    at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
    at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
    at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
    at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
    at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

And there are more... If you want i can send you all the log.

**Comment by xtomyserrax** [comment]
Hey, i cant download 1.7.10 or 1.8 because of this legal problems.

You cant download 1.8 from spigot too.

So please try to fix this... it spams all the console. I luckly have the 1.7.2

**Comment by oloflarsson** [comment]
Anyone can obtain Spigot 1.8. Just read up on how to do it.
