### ISSUE TITLE
1.7.10 Version

### ISSUE THREAD

**Issue by xtomyserrax** [MassiveCraft/Factions#768]
Hey, where can i get a factions version for 1.7.10.

Because i am using 2.7.4 and i get this error: And 2.7.5 it says its only for 1.8

[23:56:48] [Server thread/INFO]: [Factions] Enabling Factions v2.7.4
[23:56:48] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.4[0;36;22m] [0;33;1m=== ENABLE START ===[m
[23:56:48] [Server thread/ERROR]: Error occurred while enabling Factions v2.7.4 (Is it up to date?)
java.lang.RuntimeException: Failed to invoke public com.massivecraft.factions.entity.MConf() with no args
	at com.massivecraft.massivecore.xlib.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:112) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:174) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:806) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:871) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:844) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.loadFromRemote(Coll.java:626) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:859) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.init(Coll.java:947) ~[?:?]
	at com.massivecraft.factions.entity.MConfColl.init(MConfColl.java:29) ~[?:?]
	at com.massivecraft.factions.Factions.onEnable(Factions.java:130) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1571]
Caused by: java.lang.NoSuchFieldError: ACACIA_DOOR
	at com.massivecraft.factions.entity.MConf.<init>(MConf.java:498) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_25]
	at com.massivecraft.massivecore.xlib.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:104) ~[?:?]
	... 20 more
[23:56:48] [Server thread/INFO]: [Shopkeepers] Enabling Shopkeepers v1.39

**Comment by oloflarsson** [comment]
2.7.5, the latest version is what you should use. It works with 1.7.10 as well.
