### ISSUE TITLE
An error ocurred while enabling Factions v2.7.5 (Is it up to date?)

### ISSUE THREAD

**Issue by xtomyserrax** [MassiveCraft/Factions#796]
Hey, i get this error a lot! I am using spigot 1.7.10 and the last version of Factions (2.7.5). When i had a version like 2.7.4 i got an error so i use this, but this makes error too

[23:18:30] [Server thread/INFO]: [Factions] Enabling Factions v2.7.5
[23:18:30] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m=== ENABLE START ===[m
[23:18:30] [Server thread/ERROR]: Error occurred while enabling Factions v2.7.5 (Is it up to date?)
com.massivecraft.massivecore.xlib.gson.JsonSyntaxException: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated array at line 118 column 8 path $.denyCommandsTerritoryRelation.ENEMY[48]
	at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:57) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
	at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJson(DriverFlatfile.java:150) ~[?:?]
	at com.massivecraft.massivecore.store.DriverFlatfile.loadFile(DriverFlatfile.java:136) ~[?:?]
	at com.massivecraft.massivecore.store.DriverFlatfile.loadAll(DriverFlatfile.java:176) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:852) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.init(Coll.java:947) ~[?:?]
	at com.massivecraft.factions.entity.MConfColl.init(MConfColl.java:29) ~[?:?]
	at com.massivecraft.factions.Factions.onEnable(Factions.java:131) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1571]
Caused by: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated array at line 118 column 8 path $.denyCommandsTerritoryRelation.ENEMY[48]
	at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.syntaxError(JsonReader.java:1573) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.doPeek(JsonReader.java:479) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.hasNext(JsonReader.java:417) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:658) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:45) ~[?:?]
	... 21 more

**Comment by magnusulf** [comment]
This is you MConf being wrongly configured. Unterminated array at line 118 column 8
