### ISSUE TITLE
error with lockette

### ISSUE THREAD

**Issue by TonyFoster** [MassiveCraft/Factions#806]
version:
This server is running CraftBukkit version git-Spigot-c46583f-e6f9fd4 (MC: 1.8) 
[Lockette] Enabling Lockette v1.8.13
[Factions] Enabling Factions v2.7.5
[MassiveCore] Enabling MassiveCore v2.7.5

full error:
[04:21:38] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Lockette v1.8.13
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:724) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_10]
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0_10]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_10]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_10]
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/P
	at org.yi.acru.bukkit.PluginCoreLink.getFactions(PluginCoreLink.java:90) ~[?:?]
	at org.yi.acru.bukkit.PluginCore.inGroup(PluginCore.java:561) ~[?:?]
	at org.yi.acru.bukkit.PluginCore.inGroup(PluginCore.java:461) ~[?:?]
	at org.yi.acru.bukkit.Lockette.Lockette.isUser(Lockette.java:1914) ~[?:?]
	at org.yi.acru.bukkit.Lockette.LockettePlayerListener.canInteract(LockettePlayerListener.java:488) ~[?:?]
	at org.yi.acru.bukkit.Lockette.LockettePlayerListener.interactContainer(LockettePlayerListener.java:461) ~[?:?]
	at org.yi.acru.bukkit.Lockette.LockettePlayerListener.onPlayerInteract(LockettePlayerListener.java:263) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_10]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_10]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
	... 17 more

**Comment by magnusulf** [comment]
Your version of lockette (or its faction integration) is extremely outdated.
Not a bug in factions but in lockette.

**Comment by TonyFoster** [comment]
http://dev.bukkit.org/bukkit-plugins/lockette/
But I Lockette 1.8.13 already are latest version.

**Comment by TonyFoster** [comment]
Sorry, I finally understand about this, I will try to find other version of Lockette.
