### ISSUE TITLE
{factions_roleprefixforce} is broken

### ISSUE THREAD

**Issue by Mike1255** [MassiveCraft/Factions#814]
Hey Guys, 

So I'm facing an issue right now using {factions_roleprefixforce} with EssentialsChat and/or forcing Factions to modify the chat.

![chatbug](https://cloud.githubusercontent.com/assets/1573267/6307195/4586f4d8-b93a-11e4-8707-0b3e1d74bd37.png)

![config](https://cloud.githubusercontent.com/assets/1573267/6307202/54ec9248-b93a-11e4-8116-6dcc5cb1c4ee.png)

Server Version: Spigot 1.8-R0.1

Factions: 2.7.5

MassiveCore: 2.7.5

Essentials: 2.X Snapshot

**Comment by oloflarsson** [comment]
What happens if you use {factions_roleprefix}?
Does that one work for you?

**Comment by Mike1255** [comment]
Yep, that works perfectly fine it's just when I add force it doesn't.

**Comment by Mike1255** [comment]
The main reason I want to use {factions_roleprefixforce} is because it forces a "-" to be written when a player isn't in a faction, without using {factions_roleprefixforce} only "[]" is displayed when someone isn't in a faction regardless if the Recruit rank already is set to display "-".

**Comment by oloflarsson** [comment]
Oh I remember now. This bug is fixed in this recent commit: https://github.com/MassiveCraft/Factions/commit/29a4feeff69e25aee6d82c8273a6640ee86a65b8

Either compile MassiveCore and Factions yourself and use the latest development version that way, or wait for the next update of the plugin to be published on Bukkit and Spigot.

**Comment by Mike1255** [comment]
I'll be compiling this thanks! I'll keep you updated.

**Comment by Mike1255** [comment]
Here's an update, this may sound annoying but I seriously cannot get Faction's compiled, there is a MassiveCore Exception which gives out an error as for some reason it doesn't exist and other alternatives haven't worked. I'd really appreciate it if you could send a .jar based on the latest github commit if that would be possible.

**Comment by ulumulu1510** [comment]
@Mike1255
This happens when you don't compile the dev version of MassiveCore alongside with factions. MassiveExceptions is a new feature we implemented in the not yet released versions. Compiling with (per example) MassiveCore v2.7.5 will throw errors.

If you can wait, I might have time later this day to compile you the latest in dev versions of massivecore and factions.

**Comment by ulumulu1510** [comment]
@Mike1255 

I compiled the newest versions available on git for you. This zip folder contains both, MassiveCore and Factions. Use at your own risk, but they are working fine for me.

https://drive.google.com/file/d/0BxKR-QugBXv_RFFyV1NVNTN3bEk/view?usp=sharing

**Comment by Mike1255** [comment]
@ulumulu1510 

Thanks for the help provided, although for some odd reason they don't want to load on my server.

I am on the Spigot 1.8 R0.1 Snapshot.

**Comment by ulumulu1510** [comment]
@Mike1255
Does the console throw any errors? And have you unzipped and replaved the old plugin files?

**Comment by Mike1255** [comment]
@ulumulu1510 

The strange thing is they don't seem to even load I can't seem to spot any errors at all and yes I completely removed the old plugin files and had replaced them.

**Comment by Mike1255** [comment]
@ulumulu1510 

at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:744) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at org.bukkit.Bukkit.reload(Bukkit.java:534) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [minecraft_server.jar:git-Spigot-b73910a-726656b]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.lang.UnsupportedClassVersionError: com/massivecraft/massivecore/MassiveCore : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_71]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_71]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_71]
at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_71]
at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_71]
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_71]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_71]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-b73910a-726656b]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-b73910a-726656b]
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_71]
at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_71]
at java.lang.Class.forName0(Native Method) ~[?:1.7.0_71]
at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_71]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[minecraft_server.jar:git-Spigot-b73910a-726656b]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[minecraft_server.jar:git-Spigot-b73910a-726656b]
... 20 more

These are some errors I spotted but not too sure if they are related.

**Comment by ulumulu1510** [comment]
@Mike1255 
Let's talk about this on another medium perhaps. ON another note, don't use the reload command if possible.

Skype:
titanusbenjaminus

Ts:
massivecraft.com

**Comment by Mike1255** [comment]
@ulumulu1510 

Added you, thanks once again for all the help being provided. :)
