### ISSUE TITLE
Faction & CombatLog

### ISSUE THREAD

**Issue by EverMineServer** [MassiveCraft/Factions#838]
The console give me this Error and CombatLog don't work.

 Could not pass event EntityDamageByEntityEvent to CombatLog v1.8.11
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-c136710-350cb99]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c136710-350cb99]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c136710-350cb99]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c136710-350cb99]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:85) [spigot.jar:git-Spigot-c136710-350cb99]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:538) [spigot.jar:git-Spigot-c136710-350cb99]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:451) [spigot.jar:git-Spigot-c136710-350cb99]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:570) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.EntityLiving.d(EntityLiving.java:1101) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.EntityHuman.d(EntityHuman.java:859) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.EntityLiving.damageEntity(EntityLiving.java:742) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.EntityHuman.attack(EntityHuman.java:1001) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.EntityPlayer.attack(EntityPlayer.java:1060) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:1343) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c136710-350cb99]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-c136710-350cb99]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/BoardColls
        at com.jackproehl.plugins.listeners.EntityDamageByEntityListener.tagAttacker(EntityDamageByEntityListener.java:115) ~[?:?]
        at com.jackproehl.plugins.listeners.EntityDamageByEntityListener.onEntityDamageByEntity(EntityDamageByEntityListener.java:50) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c136710-350cb99]
        ... 26 more

**Comment by magnusulf** [comment]
Lol, why are you reporting this at factions when the issue is in Combatlog? That just makes no goddamn sense. Don't try to tell me something like "this only occurs when Factions are installed". The issue is in Combatlog so you should report to them. If you bought a car that didn't work you would complain to the car seller not to the local grocery store that would just be plain stupid. The same thing applies to minecraft plugins.
I read the stacktrace and I am 100% this isn't a problem in factions.

**Comment by oloflarsson** [comment]
You are using incompatible versions of Factions and CombatLog. It seems CombatLog were compiled against another version of Factions than the one you are currently using.
