### ISSUE TITLE
[2.2.2] Error on 1.6.4 build for 1.6.4.

### ISSUE THREAD

**Issue by Zilacon** [MassiveCraft/Factions#843]
I am using the latest 1.6.4 build on a 1.6.4 MCPC server and i get this error:
````
03-31 14:32:10 [SEVERE] [Minecraft] Could not pass event BlockIgniteEvent to Factions v2.2.2
org.bukkit.event.EventException
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:437)
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
 at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:31)
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
 at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.callBlockIgniteEvent(CraftEventFactory.java:702)
 at net.minecraft.block.BlockStationary.func_71847_b(BlockStationary.java:81)
 at net.minecraft.world.WorldServer.run(WorldServer.java:603)
 at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
 at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.NullPointerException
 at com.massivecraft.factions.listeners.FactionsListenerMain.blockFireSpread(FactionsListenerMain.java:706)
 at com.massivecraft.factions.listeners.FactionsListenerMain.blockFireSpread(FactionsListenerMain.java:719)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:435)
 ... 9 more
````

Is there any way you guys could make an updated version of everything you have done since your last 1.6.4 build and make a updated one for 1.6.4? A lot of servers still use factions on 1.6.4 due to modpacks.

Thanks.

**Comment by ulumulu1510** [comment]
As far as I know, with our newest versions we only support 1.7.x and upwards. It would be too much work to support every major version of minercraft/bukkit.
@oloflarsson

**Comment by oloflarsson** [comment]
Yeah. Minecraft 1.6 is really old. We aim to support 1.7 and upwards for now. You should update your server.
