### ISSUE TITLE
Could Not Load Plugin

### ISSUE THREAD

**Issue by UmmnLala** [MassiveCraft/Factions#852]
Hey all i am have an issue with Dynmap, I just bought it and installed it on a brand new server i am making.  With a fresh 1.8.3 CraftBukkit as well as 1.8.3 Spigot i am getting the following error with Dynmap only.  MassiveCore and Factions load fine and work well.  the last linesays i have java 1.8.0_45  which i checked with and my server is up to date running Ubuntu 14.04.   I also tried with the 1.8.0 Spigot and got the same error

Here is the 1.8.3 CraftBukkit error on server start:

[20:22:01 ERROR]: Could not load 'plugins/FactionsDynmap.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: dynmap
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [Minecraft.jar:git-Bukkit-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:288) [Minecraft.jar:git-Bukkit-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.<init>(CraftServer.java:250) [Minecraft.jar:git-Bukkit-7722428]
        at net.minecraft.server.v1_8_R2.PlayerList.<init>(PlayerList.java:69) [Minecraft.jar:git-Bukkit-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedPlayerList.<init>(SourceFile:14) [Minecraft.jar:git-Bukkit-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:180) [Minecraft.jar:git-Bukkit-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:501) [Minecraft.jar:git-Bukkit-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

And here is the error for 1.8.3 Spigot:

[20:39:14 ERROR]: Could not load 'plugins/FactionsDynmap.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: dynmap
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [Minecraft.jar:git-Spigot-2ec6f06-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [Minecraft.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [Minecraft.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [Minecraft.jar:git-Spigot-2ec6f06-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

Thanks for your help and time reading this!  If it is something easy or dumb i am missing don't flame, just tell me the answer or point me in the right direction.

**Comment by ulumulu1510** [comment]
@UmmnLala Your question is already full of informationand I tahnk you for this, but please hand in the full error log, since we are missing the cause of the issue in your snippet. To avoid a cluttered github, upload the full error log to pastebin or a similar service and report back, if anything has changed.

**Comment by oloflarsson** [comment]
You must install dynmap to use FactionsDynmap.
