### ISSUE TITLE
can not load plugin (first time on the server)

### ISSUE THREAD

**Issue by reschiram** [MassiveCraft/Factions#862]
This server is running CraftBukkit version git-Bukkit-17a3db7 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[16:48:03] [Server thread/ERROR]: Could not load 'plugins\Factions.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MassiveCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-17a3db7]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-17a3db7]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-17a3db7]
	at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-17a3db7]
	at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-17a3db7]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit.jar:git-Bukkit-17a3db7]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit.jar:git-Bukkit-17a3db7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:48:04] [Server thread/INFO]: [Vault] [Economy] UltimateCore found: Loaded
[16:48:04] [Server thread/WARN]: java.lang.NullPointerException
[16:48:04] [Server thread/WARN]: 	at bammerbom.ultimatecore.bukkit.r.log(r.java:351)
[16:48:04] [Server thread/WARN]: 	at bammerbom.ultimatecore.bukkit.UltimateCore.<clinit>(UltimateCore.java:62)
[16:48:04] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[16:48:04] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[16:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40)
[16:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[16:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328)
[16:48:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251)
[16:48:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288)
[16:48:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250)
[16:48:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69)
[16:48:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14)
[16:48:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133)
[16:48:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484)
[16:48:04] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by reschiram** [comment]
help i would be great if this works

**Comment by ulumulu1510** [comment]
Do you have massivecore installed? I believe you don't.

**Comment by reschiram** [comment]
no i forget it

**Comment by reschiram** [comment]
i works now

**Comment by ulumulu1510** [comment]
Then please close the issue yourself. Thanks :).
