### ISSUE TITLE
Console Log spam

### ISSUE THREAD

**Issue by Katelyn-SN** [MassiveCraft/Factions#863]
Cauldron 1.7.10 (Spigot features disabled in Factions)

Latest Factions and MassiveCore also tested Github source versions of both with same result.
```
[21:52:50 INFO]: [Factions 2.7.5] Reset data for  Katelyn . Unknown factionId 4cafaa86-5662-4285-8ef0-852d8f6e1e88
```

```
[22:00:00 WARN]: Exception in thread "Craft Scheduler Thread - 8"
[22:00:00 WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 901
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyFactionAgeBonus(EventFactionsRemovePlayerMillis.java:110)
        at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:56)
        at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
        at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
        at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:72)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by oloflarsson** [comment]
Cauldron is dead. We do not support Cauldron, sorry.
