### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by dodieboy** [MassiveCraft/Factions#878]
when i online my server i got this:
[23:26:34] [Server thread/ERROR]: Error occurred while enabling Factions v2.7.5 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method "com.massivecraft.factions.entity.Faction.setFlag(Lcom/massivecraft/factions/entity/MFlag;Z)Ljava/lang/Boolean;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/massivecraft/factions/entity/FactionColl, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/massivecraft/factions/entity/Faction, have different Class objects for the type com/massivecraft/factions/entity/MFlag used in the signature
	at com.massivecraft.factions.entity.FactionColl.getSafezone(FactionColl.java:127) ~[?:?]
	at com.massivecraft.factions.entity.FactionColl.createSpecialFactions(FactionColl.java:78) ~[?:?]
	at com.massivecraft.factions.entity.FactionColl.init(FactionColl.java:36) ~[?:?]
	at com.massivecraft.factions.Factions.onEnable(Factions.java:136) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:72) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:124) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) [PerWorldPlugins.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:625) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1079) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:939) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:676) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [craftbukkit-1.8.6.jar:git-Bukkit-5084899]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]

and the plugin cannot run after that

**Comment by dodieboy** [comment]
my other plugin crasg it
