### ISSUE TITLE
Here is something wrong in Spigot 1.8.6

### ISSUE THREAD

**Issue by shenmadetoufa** [MassiveCraft/Factions#885]
Here is something wrong in Spigot 1.8.6
This is the crash.
Can you fix this ?
Thank you very much 
[09:09:36] [Server thread/ERROR]: Could not pass event PotionSplashEvent to Factions v2.7.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:327) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityPotion.a(EntityPotion.java:93) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:154) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at org.bukkit.potion.Potion.fromDamage(Potion.java:408) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at com.massivecraft.massivecore.util.MUtil.getPotionEffects(MUtil.java:733) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:770) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:782) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.canCombatDamageHappen(EngineMain.java:814) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	... 15 more
[09:09:40] [Server thread/ERROR]: Could not pass event PotionSplashEvent to Factions v2.7.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:327) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityPotion.a(EntityPotion.java:93) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:154) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at org.bukkit.potion.Potion.fromDamage(Potion.java:408) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at com.massivecraft.massivecore.util.MUtil.getPotionEffects(MUtil.java:733) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:770) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:782) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.canCombatDamageHappen(EngineMain.java:814) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	... 15 more
[09:09:43] [Server thread/ERROR]: Could not pass event PotionSplashEvent to Factions v2.7.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:327) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityPotion.a(EntityPotion.java:93) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:154) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at org.bukkit.potion.Potion.fromDamage(Potion.java:408) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at com.massivecraft.massivecore.util.MUtil.getPotionEffects(MUtil.java:733) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:770) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:782) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.canCombatDamageHappen(EngineMain.java:814) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	... 15 more
[09:09:57] [Server thread/ERROR]: Could not pass event PotionSplashEvent to Factions v2.7.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:327) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityPotion.a(EntityPotion.java:93) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:154) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at org.bukkit.potion.Potion.fromDamage(Potion.java:408) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at com.massivecraft.massivecore.util.MUtil.getPotionEffects(MUtil.java:733) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:770) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:782) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.canCombatDamageHappen(EngineMain.java:814) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	... 15 more
[09:10:54] [Server thread/WARN]: Nian moved wrongly!
[09:11:09] [Server thread/ERROR]: Could not pass event PotionSplashEvent to Factions v2.7.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:327) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityPotion.a(EntityPotion.java:93) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:154) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at org.bukkit.potion.Potion.fromDamage(Potion.java:408) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	at com.massivecraft.massivecore.util.MUtil.getPotionEffects(MUtil.java:733) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:770) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.isHarmfulPotion(MUtil.java:782) ~[?:?]
	at com.massivecraft.factions.engine.EngineMain.canCombatDamageHappen(EngineMain.java:814) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.6-1.jar:git-Spigot-044d928-e8c6403]
	... 15 more

**Comment by MarkehMe** [comment]
Are you able to replicate this in 2.8.0? What version of MassiveCore are you using? 

http://dev.bukkit.org/bukkit-plugins/factions/files/76-factions-2-8-0/

**Comment by magnusulf** [comment]
Inactive. Closing.
