### ISSUE TITLE
An error ocurred while enabling Factions v2.7.5 (Is it up to date?)

### ISSUE THREAD

**Issue by Worivee** [MassiveCraft/Factions#894]
Hey, i get this error a lot! I am using spigot 1.7.10 and the last version of Factions (2.7.5). When i had a version like 2.7.4 i got an error so i use this, but this makes error too
 
[ERROR] Error occurred while enabling Factions v2.7.5 (Is it up to date?)
com.massivecraft.massivecore.xlib.gson.JsonSyntaxException: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:65) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJson(DriverFlatfile.java:150) ~[?:?]
at com.massivecraft.massivecore.store.DriverFlatfile.loadFile(DriverFlatfile.java:136) ~[?:?]
at com.massivecraft.massivecore.store.DriverFlatfile.loadAll(DriverFlatfile.java:176) ~[?:?]
at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:852) ~[?:?]
at com.massivecraft.massivecore.store.Coll.init(Coll.java:947) ~[?:?]
at com.massivecraft.factions.entity.MFlagColl.init(MFlagColl.java:32) ~[?:?]
at com.massivecraft.factions.Factions.onEnable(Factions.java:129) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[minecraft_server.jar:git-Spigot-1627]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [minecraft_server.jar:git-Spigot-1627]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-1627]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [minecraft_server.jar:git-Spigot-1627]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [minecraft_server.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [minecraft_server.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [minecraft_server.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [minecraft_server.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [minecraft_server.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [minecraft_server.jar:git-Spigot-1627]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1627]
Caused by: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.syntaxError(JsonReader.java:1573) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.checkLenient(JsonReader.java:1422) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.doPeek(JsonReader.java:545) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.peek(JsonReader.java:428) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:60) ~[?:?]
... 19 more

**Comment by oloflarsson** [comment]
You have malformed a configuration file or some other file in the database.
