### ISSUE TITLE
Factions 2.7.4 , Loads with no commands !

### ISSUE THREAD

**Issue by conetopia** [MassiveCraft/Factions#921]
Factions 2.7.4 , and Mcore 2.7.4
Running a Cauldron 1.7.10 server.
no mods currently added.
Ran over 34 different versions of 1.7.10 cauldron.
in-game when i type /plugins, factions does show...
but when you do /f or try any commands, nothing is available/listed. 
server pretends the plugin does not exist..
Maybe i need to remove acacia_door from the factions plugin?
Any updates? compatibility version ? ect ?

[12:51:23] [Server thread/INFO]: [Factions 2.7.4] === ENABLE START ===
[12:51:23] [Server thread/ERROR]: Error occurred while enabling Factions v2.7.4 (Is it up to date?)
java.lang.NoSuchFieldError: ACACIA_DOOR
	at com.massivecraft.factions.entity.MConf.<init>(MConf.java:498) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_51]
	at com.massivecraft.massivecore.store.Coll.createNewInstance(Coll.java:258) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.create(Coll.java:282) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.get(Coll.java:120) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.get(Coll.java:111) ~[?:?]
	at com.massivecraft.factions.entity.MConfColl.init(MConfColl.java:30) ~[?:?]
	at com.massivecraft.factions.Factions.onEnable(Factions.java:130) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1492.152]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1492.152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1492.152]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1492.152]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1492.152]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]

**Comment by conetopia** [comment]
Note: factions 2.7.5 with Mcore 2.7.5 loads, and is fully functional, but after saving the server, closing the server, turning the server back on... all factions still listed, all protection is fully working ect.
But then there is an error saying connection list severed or something like that.
Always happens after first restart.

Doing the report on 2.7.4 since its supposed to be made and support 1.7.10 to begin with.

**Comment by conetopia** [comment]
Updated to factions 2.8.0 , and mcore 2.8.0 
same issue as 2.7.5
me and a few players made some factions, claimed land.
saved server, stopped, started server again
went to claim more land, and got a message saying  commandsender link has been severed.

so we have 2.7.4 with no commands.
then we have 2.7.5 or later... with same error? wtf am i missing?
just mcore is the only dependency right?
I don't need multiverse or anything like that correct?

**Comment by conetopia** [comment]
After reading some pages on google, I found out that this is a common issue for Cauldron.
The Dev team doesn't care to support / help with Cauldron , because they believe that Cauldron is dead. Its actually very popular, Especially for the Aether II community.

Hope a single individual would eventually arise and take the challenge to add cauldron support.

**Comment by oloflarsson** [comment]
Cauldron is not supported. Feel free to create a pull request adding Cauldron support since we do not have the time to develop that ourselves.
