### ISSUE TITLE
Issue with /f claim fill

### ISSUE THREAD

**Issue by DaFriendlySentry** [MassiveCraft/Factions#933]
I'm using Spigot 1.8.7, connecting via bungeecord proxy. Using the latest version of factions.
----------------------------------------------------------------------------------------------------------------------------
[04:27:29] [Server thread/INFO]: DaFriendlySentry issued server command: /f claim fill
[04:27:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f claim fill' in com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand(f)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException: pss
	at com.massivecraft.factions.entity.MPlayer.tryClaim(MPlayer.java:812) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsSetX.perform(CmdFactionsSetX.java:53) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:599) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:578) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:578) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:631) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot40.jar:git-Spigot-ec3f46e-2359f6f]
	... 14 more

**Comment by MarkehMe** [comment]
Please provide your version of Factions and MassiveCore :smiley:

**Comment by magnusulf** [comment]
Incomplete and inactive. Closing.
