### ISSUE TITLE
Issue with Factions

### ISSUE THREAD

**Issue by Buildsoccer4me** [MassiveCraft/Factions#935]
I have an issue with factions:

In factions whenever I try to create a faction it tells me to leave my current faction and then when I do /f leave it says internal error. And also in my console it spams this message:

Reset data for [Player}. Unkown factionId 83b654c-e232-4cfo-a8f1-34cbbb6cd525 and it is a different name for everyone.

So this shows on my console Pail every time I run factions:

10:57 PM [SEVERE] Could not pass event PlayerJoinEvent to Factions v2.8.1 
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.engine.EngineMain.motd(EngineMain.java:399)
	at com.massivecraft.factions.engine.EngineMain.motdLowest(EngineMain.java:432)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:296)
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156)
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
	at java.lang.Thread.run(Thread.java:745)
10:57 PM [INFO] [Vault] No new version available 
10:57 PM [SEVERE] Could not pass event PlayerJoinEvent to Factions v2.8.1 
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.engine.EngineMain.motd(EngineMain.java:399)
	at com.massivecraft.factions.engine.EngineMain.motdLow(EngineMain.java:439)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:296)
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156)
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
	at java.lang.Thread.run(Thread.java:745)
10:57 PM [INFO] [Paintball] --------- Serverlist ---------- 
10:57 PM [INFO] [Paintball] Wasn't able to post server: Read timed out 
10:57 PM [INFO] [Paintball] Maybe the master server is down or has bad latency. 
10:57 PM [INFO] [Paintball] --------- ---------------- ---------- 
10:57 PM [INFO] [Paintball] --------- Checking version ---------- 
10:57 PM [INFO] [Paintball] There is a new version of paintball available: Paintball v1.3.4 (RELEASE) 
10:57 PM [INFO] [Paintball] Download at the bukkit dev page. 
10:57 PM [INFO] [Paintball] --------- ---------------- ---------- 
10:57 PM [SEVERE] Could not pass event PlayerJoinEvent to Factions v2.8.1 
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.engine.EngineMain.motd(EngineMain.java:399)
	at com.massivecraft.factions.engine.EngineMain.motdMonitor(EngineMain.java:467)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:296)
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156)
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
	at java.lang.Thread.run(Thread.java:745)
10:57 PM [WARNING] [Essentials] Task #156 for Essentials vTeamCity generated an exception 
java.lang.NoClassDefFoundError: com/earth2me/essentials/xmpp/XMPPManager
	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:123)
	at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:35)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
	at java.lang.Thread.run(Thread.java:745)
10:57 PM [SEVERE] Could not pass event PlayerCommandPreprocessEvent to Factions v2.8.1 
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.engine.EngineMain.denyCommands(EngineMain.java:1084)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1127)
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
	at java.lang.Thread.run(Thread.java:745)
10:57 PM [SEVERE] Could not pass event PlayerCommandPreprocessEvent to Factions v2.8.1 
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.engine.EngineMain.denyCommands(EngineMain.java:1084)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1127)
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
	at java.lang.Thread.run(Thread.java:745)
10:59 PM [SEVERE] Could not pass event PlayerCommandPreprocessEvent to Factions v2.8.1 
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.engine.EngineMain.denyCommands(EngineMain.java:1084)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1127)
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ulumulu1510** [comment]
Please state your version of MassiveCore, Factions and Spigot you are running currently. And also, whether you run your server in online or offline mode.

Please use pastebin or another code pasting website to provide us with the full error log, because that line is not like its printed in the console.

**Comment by magnusulf** [comment]
Incomplete and inactive. Closing.
