### ISSUE TITLE
at the connection of a player with a faction all other players are kick of the server

### ISSUE THREAD

**Issue by ByReturn** [MassiveCraft/Factions#944]
at the connection of a player with a faction all other players are kick of the server

faction version:  FactionsUUID-1.6.9.5.jar

Error log: 
Shakatu[/109.215.125.97:52154] logged in with entity id 1623 at ([monde] 35.69999998807907, 71.0, 33.998040158259116)
[21:59:14] [Netty IO #3/WARN]:  at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
[21:59:14] [Netty IO #3/WARN]:  at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
[21:59:14] [Netty IO #3/WARN]:  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
[21:59:14] [Netty IO #3/WARN]:  at sun.nio.ch.IOUtil.read(IOUtil.java:192)
[21:59:14] [Netty IO #3/WARN]:  at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
[21:59:14] [Netty IO #3/WARN]:  at net.minecraft.util.io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436)
[21:59:14] [Netty IO #3/WARN]:  at net.minecraft.util.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870)
[21:59:14] [Netty IO #3/WARN]:  at net.minecraft.util.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
[21:59:14] [Netty IO #3/WARN]:  at net.minecraft.util.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87)
[21:59:14] [Netty IO #3/WARN]:  at net.minecraft.util.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
[21:59:14] [Netty IO #3/WARN]:  at net.minecraft.util.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
[21:59:14] [Netty IO #3/WARN]:  at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
[21:59:14] [Netty IO #3/WARN]:  at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
[21:59:14] [Netty IO #3/WARN]:  at java.lang.Thread.run(Thread.java:745)
[21:59:14] [Server thread/INFO]: [-] ByReturn

as you can see that when the player "Shakatu" is connected there is a mistake and that the player deconecte "ByReturn"

Please help me <3

**Comment by MarkehMe** [comment]
FactionsUUID uses Factions 1.6.x, which is not supported (it's REALLY old, MassiveCraft disbanded it on the [23rd of April 2013](https://github.com/MassiveCraft/Factions/commit/10f9c164614ea78219c54e1ed5085bb1898c9087)). I cant see any reference in yours tack trace to MassiveCraft Factions.

You can upgrade to Factions 2.8.0 here: http://dev.bukkit.org/bukkit-plugins/factions/files/76-factions-2-8-0/

You need MassiveCore too: http://dev.bukkit.org/bukkit-plugins/mcore/files/44-massive-core-2-8-0/

Let me know if I can help you any other way. Good luck!
