### ISSUE TITLE
Won't load in server

### ISSUE THREAD

**Issue by lvvipervvi** [MassiveCraft/Factions#954]
I keep get an error when loading fractions in the server window:

[17:01:35 ERROR]: Could not load 'plugins/Factions.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MassiveCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by MarkehMe** [comment]
```org.bukkit.plugin.UnknownDependencyException: MassiveCore```

You need the MassiveCore plugin. You can grab it from here: 

https://www.spigotmc.org/resources/massivecore.1901/

**Comment by crazyzap121** [comment]
I know this will sound very stupid but don't judge i'm new
How do we get the plugin into out minecraft? Is it a resourse pack or what please help
