### ISSUE TITLE
Won't start up

### ISSUE THREAD

**Issue by ItzDan** [MassiveCraft/Factions#958]
[07:30:32] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.2[0;36;22m] [0;33;1m=== ENABLE START ===[m
[07:30:32] [Server thread/ERROR]: Error occurred while enabling Factions v2.8.2 (Is it up to date?)
java.lang.NoSuchMethodError: com.massivecraft.massivecore.store.Coll.<init>(Ljava/lang/String;Ljava/lang/Class;Lcom/massivecraft/massivecore/store/Db;Lorg/bukkit/plugin/Plugin;ZZZ)V
at com.massivecraft.factions.entity.MFlagColl.<init>(MFlagColl.java:21) ~[?:?]
at com.massivecraft.factions.entity.MFlagColl.<clinit>(MFlagColl.java:17) ~[?:?]
at com.massivecraft.factions.Factions.onEnable(Factions.java:129) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [minecraft_server.jar:git-Spigot-fdc1440-53fac9f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by ulumulu1510** [comment]
Are you eventually running versions of MassiveCore and Factions? This could cause your issues.

But please state your Versions of:
* Factions
* MassiveCore
* Bukkit/Spigot

**Comment by ItzDan** [comment]
Factions: 
MassiveCore: 2.8.0
Spigot: git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by ulumulu1510** [comment]
Well, the logs provided in xour post show that you use factions 2.8.2, so you have to update MassiveCore to 2.8.2 aswell.

**Comment by ItzDan** [comment]
Thanks, That fixed it.
