### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to Factions

### ISSUE THREAD

**Issue by carelli99** [MassiveCraft/Factions#973]
Hello, sometimes i find on my console this error:
```
15.11 15:19:04 [Multicraft] Skipped 16 lines due to rate limit (30/s)
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.t_(EntityZombie.java:221) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.t_(EntityMonster.java:24) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.m(EntityZombie.java:163) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.m(EntityMonster.java:20) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1626) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:473) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.PathfinderGoalMeleeAttack.e(SourceFile:122) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.r(EntityZombie.java:225) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.r(EntityMonster.java:72) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
15.11 15:19:03 [Server] INFO org.bukkit.event.EventException
15.11 15:19:03 [Server] ERROR Could not pass event EntityDamageByEntityEvent to Factions v2.8.0
 ```
Help?

**Comment by MarkehMe** [comment]
Multicraft has cut off the import parts of this error message. Could you please find it in your server log and share it with us. Please upload it to pastebin or wrapper it with a code block using Markdown as it is difficult to read in plaintext! 

What version of MassiveCore do you have? Use the command ```/mcore version``` to find it!

**Comment by carelli99** [comment]
Ok man, thanks for reply. Here you can find error: http://pastebin.com/0nVdLS8Y
My version of MassiveCore: 2.8.0

**Comment by MarkehMe** [comment]
```Double.isFinite``` is a method that can only be used in Java 8, what version of Java are you using - can you upgrade to Java 8?

**Comment by ulumulu1510** [comment]
We have fixed this issue a long time ago, please update to any higher version ti fix the issues.
