### ISSUE TITLE
/f claim square 100000 results in "The server has stopped responding!"

### ISSUE THREAD

**Issue by dossy** [MassiveCraft/Factions#979]
Presumably this simply took too long and some deadlock detection triggered since the command took too long.  This is a default install of Factions, so I haven't configured anything.  Perhaps the default limit is too high (or not set at all)? Checking now, `factions_mconf/instance.json` has `claimedLandsMax = 0`.  It does have `setRadiusMax = 30`, though.

It looks like the server hit an OOM (out of memory) error.

This is on Factions 2.8.2, git-Spigot-db6de12-18fbb24 (MC: 1.8.8).

```
[10:50:35 INFO]: xDatCookieDoughx issued server command: /f claim square 100000
[10:51:42 ERROR]: The server has stopped responding!
[10:51:42 ERROR]: Please report this to http://www.spigotmc.org/
[10:51:42 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[10:51:42 ERROR]: Spigot version: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Server thread dump (Look for plugins here before reporting to Spigot!):
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Server thread
[10:51:42 ERROR]:       PID: 15 | Suspended: false | Native: false | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.util.zip.ZipFile.read(Native Method)
[10:51:42 ERROR]:               java.util.zip.ZipFile.access$1400(ZipFile.java:56)
[10:51:42 ERROR]:               java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:679)
[10:51:42 ERROR]:               java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:415)
[10:51:42 ERROR]:               java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[10:51:42 ERROR]:               sun.misc.Resource.getBytes(Resource.java:124)
[10:51:42 ERROR]:               java.net.URLClassLoader.defineClass(URLClassLoader.java:444)
[10:51:42 ERROR]:               java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[10:51:42 ERROR]:               java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[10:51:42 ERROR]:               java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[10:51:42 ERROR]:               java.security.AccessController.doPrivileged(Native Method)
[10:51:42 ERROR]:               java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[10:51:42 ERROR]:               java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[10:51:42 ERROR]:               sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[10:51:42 ERROR]:               java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:146)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:146)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:153)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1167)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[10:51:42 ERROR]:               java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[10:51:42 ERROR]:               java.util.concurrent.FutureTask.run(FutureTask.java:262)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Entire Thread Dump:
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: process reaper
[10:51:42 ERROR]:       PID: 449 | Suspended: false | Native: false | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: User Authenticator #4
[10:51:42 ERROR]:       PID: 448 | Suspended: false | Native: false | State: RUNNABLE
[10:51:42 ERROR]:       Thread is waiting on monitor(s):
[10:51:42 ERROR]:               Locked on:sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
[10:51:42 ERROR]:               Locked on:sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
[10:51:42 ERROR]:               Locked on:sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
[10:51:42 ERROR]:               Locked on:sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1302)
[10:51:42 ERROR]:               Locked on:sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               javax.security.auth.x500.X500Principal.equals(X500Principal.java:461)
[10:51:42 ERROR]:               java.security.cert.X509CertSelector.match(X509CertSelector.java:2051)
[10:51:42 ERROR]:               sun.security.provider.certpath.AdaptableX509CertSelector.match(AdaptableX509CertSelector.java:185)
[10:51:42 ERROR]:               sun.security.provider.certpath.PKIXCertPathValidator.isWorthTrying(PKIXCertPathValidator.java:246)
[10:51:42 ERROR]:               sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:171)
[10:51:42 ERROR]:               java.security.cert.CertPathValidator.validate(CertPathValidator.java:279)
[10:51:42 ERROR]:               sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:345)
[10:51:42 ERROR]:               sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249)
[10:51:42 ERROR]:               sun.security.validator.Validator.validate(Validator.java:260)
[10:51:42 ERROR]:               sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
[10:51:42 ERROR]:               sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[10:51:42 ERROR]:               sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
[10:51:42 ERROR]:               sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1454)
[10:51:42 ERROR]:               sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
[10:51:42 ERROR]:               sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
[10:51:42 ERROR]:               sun.security.ssl.Handshaker.process_record(Handshaker.java:849)
[10:51:42 ERROR]:               sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
[10:51:42 ERROR]:               sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
[10:51:42 ERROR]:               sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
[10:51:42 ERROR]:               sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
[10:51:42 ERROR]:               sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[10:51:42 ERROR]:               sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[10:51:42 ERROR]:               sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1302)
[10:51:42 ERROR]:               sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[10:51:42 ERROR]:               com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:126)
[10:51:42 ERROR]:               com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54)
[10:51:42 ERROR]:               com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.hasJoinedServer(YggdrasilMinecraftSessionService.java:95)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.LoginListener$3.run(LoginListener.java:201)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Chunk I/O Executor Thread-1
[10:51:42 ERROR]:       PID: 41 | Suspended: false | Native: false | State: WAITING
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               sun.misc.Unsafe.park(Native Method)
[10:51:42 ERROR]:               java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
[10:51:42 ERROR]:               java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
[10:51:42 ERROR]:               java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[10:51:42 ERROR]:               java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
[10:51:42 ERROR]:               java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[10:51:42 ERROR]:               java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Netty Epoll Server IO #3
[10:51:42 ERROR]:       PID: 27 | Suspended: false | Native: true | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               io.netty.channel.epoll.Native.epollWait(Native Method)
[10:51:42 ERROR]:               io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
[10:51:42 ERROR]:               io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
[10:51:42 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Netty Epoll Server IO #2
[10:51:42 ERROR]:       PID: 26 | Suspended: false | Native: true | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               io.netty.channel.epoll.Native.epollWait(Native Method)
[10:51:42 ERROR]:               io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
[10:51:42 ERROR]:               io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
[10:51:42 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: File IO Thread
[10:51:42 ERROR]:       PID: 37 | Suspended: false | Native: false | State: TIMED_WAITING
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.lang.Thread.sleep(Native Method)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.FileIOThread.c(FileIOThread.java:52)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.FileIOThread.run(FileIOThread.java:28)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Netty Epoll Server IO #1
[10:51:42 ERROR]:       PID: 25 | Suspended: false | Native: true | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               io.netty.channel.epoll.Native.epollWait(Native Method)
[10:51:42 ERROR]:               io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
[10:51:42 ERROR]:               io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
[10:51:42 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: RCON Listener #1
[10:51:42 ERROR]:       PID: 31 | Suspended: false | Native: true | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.net.PlainSocketImpl.socketAccept(Native Method)
[10:51:42 ERROR]:               java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
[10:51:42 ERROR]:               java.net.ServerSocket.implAccept(ServerSocket.java:530)
[10:51:42 ERROR]:               java.net.ServerSocket.accept(ServerSocket.java:498)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.RemoteControlListener.run(SourceFile:65)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Timer-0
[10:51:42 ERROR]:       PID: 30 | Suspended: false | Native: false | State: TIMED_WAITING
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.lang.Object.wait(Native Method)
[10:51:42 ERROR]:               java.util.TimerThread.mainLoop(Timer.java:552)
[10:51:42 ERROR]:               java.util.TimerThread.run(Timer.java:505)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: MStore ExamineThread
[10:51:42 ERROR]:       PID: 29 | Suspended: false | Native: false | State: TIMED_WAITING
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.lang.Thread.sleep(Native Method)
[10:51:42 ERROR]:               com.massivecraft.massivecore.store.ExamineThread.run(ExamineThread.java:55)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Netty Epoll Server IO #0
[10:51:42 ERROR]:       PID: 24 | Suspended: false | Native: true | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               io.netty.channel.epoll.Native.epollWait(Native Method)
[10:51:42 ERROR]:               io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
[10:51:42 ERROR]:               io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
[10:51:42 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Spigot Metrics Thread
[10:51:42 ERROR]:       PID: 22 | Suspended: false | Native: false | State: TIMED_WAITING
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.lang.Object.wait(Native Method)
[10:51:42 ERROR]:               java.util.TimerThread.mainLoop(Timer.java:552)
[10:51:42 ERROR]:               java.util.TimerThread.run(Timer.java:505)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Spigot Watchdog Thread
[10:51:42 ERROR]:       PID: 21 | Suspended: false | Native: false | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               sun.management.ThreadImpl.dumpThreads0(Native Method)
[10:51:42 ERROR]:               sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
[10:51:42 ERROR]:               org.spigotmc.WatchdogThread.run(WatchdogThread.java:76)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Server console handler
[10:51:42 ERROR]:       PID: 18 | Suspended: false | Native: true | State: RUNNABLE
[10:51:42 ERROR]:       Thread is waiting on monitor(s):
[10:51:42 ERROR]:               Locked on:java.io.BufferedInputStream.read(BufferedInputStream.java:254)
[10:51:42 ERROR]:               Locked on:org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
[10:51:42 ERROR]:               Locked on:org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261)
[10:51:42 ERROR]:               Locked on:org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198)
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.io.FileInputStream.readBytes(Native Method)
[10:51:42 ERROR]:               java.io.FileInputStream.read(FileInputStream.java:272)
[10:51:42 ERROR]:               java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
[10:51:42 ERROR]:               java.io.BufferedInputStream.read(BufferedInputStream.java:254)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2349)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.DedicatedServer$2.run(DedicatedServer.java:79)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Thread-5
[10:51:42 ERROR]:       PID: 19 | Suspended: false | Native: true | State: RUNNABLE
[10:51:42 ERROR]:       Thread is waiting on monitor(s):
[10:51:42 ERROR]:               Locked on:java.io.BufferedInputStream.read(BufferedInputStream.java:254)
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.io.FileInputStream.readBytes(Native Method)
[10:51:42 ERROR]:               java.io.FileInputStream.read(FileInputStream.java:272)
[10:51:42 ERROR]:               java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
[10:51:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f claim square 100000' in com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand(f)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_91]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.massivecraft.massivecore.ps.PS.withChunkZ(PS.java:183) ~[?:?]
        at com.massivecraft.factions.cmd.CmdFactionsSetSquare.getChunks(CmdFactionsSetSquare.java:60) ~[?:?]
        at com.massivecraft.factions.cmd.CmdFactionsSetX.perform(CmdFactionsSetX.java:50) ~[?:?]
        at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:617) ~[?:?]
        at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:596) ~[?:?]
        at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:596) ~[?:?]
        at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:649) ~[?:?]
        at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        ... 14 more
[10:51:42 INFO]: xDatCookieDoughx lost connection: Disconnected
[10:51:42 INFO]: Disconnecting /96.56.31.42:1606: Failed to verify username!
[10:51:42 ERROR]: Username 'xDatCookieDoughx' tried to join with an invalid session
[10:51:42 ERROR]:               java.io.BufferedInputStream.read(BufferedInputStream.java:254)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:204)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:186)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:181)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.TerminalLineSettings.get(TerminalLineSettings.java:74)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.TerminalLineSettings.getProperty(TerminalLineSettings.java:95)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.UnixTerminal.getWidth(UnixTerminal.java:76)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.drawBuffer(ConsoleReader.java:879)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.drawBuffer(ConsoleReader.java:898)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.drawLine(ConsoleReader.java:608)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.v1_8_R3.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:38)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: DestroyJavaVM
[10:51:42 ERROR]:       PID: 17 | Suspended: false | Native: false | State: RUNNABLE
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Server thread
[10:51:42 ERROR]:       PID: 15 | Suspended: false | Native: false | State: RUNNABLE
[10:51:42 ERROR]:       Thread is waiting on monitor(s):
[10:51:42 ERROR]:               Locked on:java.util.zip.ZipFile.getEntry(ZipFile.java:306)
[10:51:42 ERROR]:               Locked on:java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.util.zip.ZipFile.getEntry(Native Method)
[10:51:42 ERROR]:               java.util.zip.ZipFile.getEntry(ZipFile.java:306)
[10:51:42 ERROR]:               java.util.jar.JarFile.getEntry(JarFile.java:227)
[10:51:42 ERROR]:               java.util.jar.JarFile.getJarEntry(JarFile.java:210)
[10:51:42 ERROR]:               sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:840)
[10:51:42 ERROR]:               sun.misc.URLClassPath.getResource(URLClassPath.java:199)
[10:51:42 ERROR]:               java.net.URLClassLoader$1.run(URLClassLoader.java:358)
[10:51:42 ERROR]:               java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[10:51:42 ERROR]:               java.security.AccessController.doPrivileged(Native Method)
[10:51:42 ERROR]:               java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[10:51:42 ERROR]:               java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[10:51:42 ERROR]:               sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[10:51:42 ERROR]:               java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[10:51:42 ERROR]:               org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:114)
[10:51:42 ERROR]:               org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:90)
[10:51:42 ERROR]:               org.apache.logging.log4j.core.impl.DefaultLogEventFactory.createEvent(DefaultLogEventFactory.java:49)
[10:51:42 ERROR]:               org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:365)
[10:51:42 ERROR]:               org.apache.logging.log4j.core.Logger.log(Logger.java:110)
[10:51:42 ERROR]:               org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.v1_8_R3.util.ForwardLogHandler.publish(ForwardLogHandler.java:33)
[10:51:42 ERROR]:               java.util.logging.Logger.log(Logger.java:616)
[10:51:42 ERROR]:               java.util.logging.Logger.doLog(Logger.java:641)
[10:51:42 ERROR]:               java.util.logging.Logger.log(Logger.java:730)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1168)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[10:51:42 ERROR]:               java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[10:51:42 ERROR]:               java.util.concurrent.FutureTask.run(FutureTask.java:262)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: Server Infinisleeper
[10:51:42 ERROR]:       PID: 16 | Suspended: false | Native: false | State: TIMED_WAITING
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.lang.Thread.sleep(Native Method)
[10:51:42 ERROR]:               net.minecraft.server.v1_8_R3.DedicatedServer$1.run(DedicatedServer.java:54)
[10:51:42 ERROR]: ------------------------------
[10:51:42 ERROR]: Current Thread: NonBlockingInputStreamThread
[10:51:42 ERROR]:       PID: 13 | Suspended: false | Native: false | State: WAITING
[10:51:42 ERROR]:       Stack:
[10:51:42 ERROR]:               java.lang.Object.wait(Native Method)
[10:51:42 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:278)
[10:51:42 ERROR]:               java.lang.Thread.run(Thread.java:745)
```

**Comment by dossy** [comment]
Upon further digging, it appears that if the user is opped, it ignores `setRadiusMax`.  I suppose that makes sense, but could lead to accidental crashing of the server with an OOM.

**Comment by ulumulu1510** [comment]
100000 chunks square is 10000000000 chunks. Frankly, almost no machine is able to handle that amount.

We assumed no admin would be so uncautious to select a number this high. It is an equivalent of editing 100000^2 blocks in WE, which also crashes your server.

Frankly, we were wrong. We will consider adding an upper limit to what a normal machine can handle. For the time being, please be aware of how much stress you are causing by adding this many chunks to a faction at a time and lower the amounts drasticly.

**Comment by dossy** [comment]
Oh, it's an absolutely unreasonable amount.  It was a test to see what would happen, to try and find ways that users could crash the server, even op's.

Having sane upper limits to prevent intentional or even accidental crashes is probably a good idea.  An op that tries to claim even 1000 square chunks (e.g., 1,000,000 chunks) might easily exceed a very small server, and could be an easy typo of adding an extra 0 to "100" which might be a lot more reasonable.

Thanks for looking into this with me.

**Comment by MarkehMe** [comment]
Thank you for doing some testing and looking for bugs! It's really appreciated :smiley:

**Comment by dossy** [comment]
Sure thing!  I've finally given in and am in the process of standing up a MC server for my kids, and Factions was one of their highly-requested plugins.  Contributing back to open source projects is something I enjoy doing.  ;-)

**Comment by MarkehMe** [comment]
Great to hear! :smile: Hope your kids are enjoy it.
